// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-ILVHS3C2.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-N4SVWGDY.js";
import { stdin_default } from "./chunks/chunk-UNQN4VUP.js";
import "./chunks/chunk-IICRMQVR.js";
import { className, css, fonts } from "./chunks/chunk-MBDBQ6CG.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:404
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/404-OWwis.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/m1jYfIz1GVuOGUgp2Uvf/IjJ4f9qs2K5sJ0jOM24m/ubCiarRXL.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Plus Jakarta Sans-medium",
	"FS;Plus Jakarta Sans-bold",
	"FS;Plus Jakarta Sans-bold italic",
	"FS;Plus Jakarta Sans-medium italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/3U7D2WJULAFN5UCDE2DSKFPDTJNUSRPY/XTZGHUDFURQVBRVTOPX7XHP5YBIQJL2U/FVNNCZHGTHUOM3RCJDOO45QMBIJISVEG.woff2",
				weight: "500",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/AJVGEOXGB2ALQKAZEK2LDOLCVBCMCOIT/LDEP4R7SNNABDEG433DCQGM2A7YCBHLU/OWABOLGBAKFVLPZ756IYS6EKYKU54K3I.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/57U2OK2BISA74Z4RT4CRD5GR4O3PNVPY/K4TDAPUNBYK24HOCNW4JIOTEXSAE2BEF/GV5XODI2YD2DJA5RVTMJOSDHYESL7IYT.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/UABF25CCX23LBLOOMOCUSPFEXYUNKOIQ/NGF5IU7BZUA2FUOVWECHGUFSHNEIX4YK/QDINYT7WQXBD2IDFQGGJ74DWIUFHOOZD.woff2",
				weight: "500",
			},
		],
	},
];
var css4 = [
	'.framer-6DSG0 .framer-styles-preset-kwq25o:not(.rich-text-wrapper), .framer-6DSG0 .framer-styles-preset-kwq25o.rich-text-wrapper h1 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, #121212); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-6DSG0 .framer-styles-preset-kwq25o:not(.rich-text-wrapper), .framer-6DSG0 .framer-styles-preset-kwq25o.rich-text-wrapper h1 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 56px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, #121212); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-6DSG0 .framer-styles-preset-kwq25o:not(.rich-text-wrapper), .framer-6DSG0 .framer-styles-preset-kwq25o.rich-text-wrapper h1 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 48px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, #121212); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className4 = "framer-6DSG0";

// /:https://framer.com/m/404-OWwis.js
var ButtonPrimaryFonts = getFonts(stdin_default);
var cycleOrder = ["irTWLuvdP", "fNHbFKi0D", "HYpK9aD2Y"];
var serializationHash = "framer-UiAQ7";
var variantClassNames = {
	fNHbFKi0D: "framer-v-176eg9w",
	HYpK9aD2Y: "framer-v-r85405",
	irTWLuvdP: "framer-v-14xa0io",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "irTWLuvdP",
	Phone: "HYpK9aD2Y",
	Tablet: "fNHbFKi0D",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "irTWLuvdP",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "irTWLuvdP",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className4, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14xa0io",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"irTWLuvdP"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								fNHbFKi0D: {
									"data-framer-name": "Tablet",
								},
								HYpK9aD2Y: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1foqma2"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"DoPuZtvEl"}
						>
							<motion.div
								className={"framer-37xrg3"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"QbWLQiC4u"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-mrrxzt"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"J1pbtSb4g"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-11asbfe"}
											data-styles-preset={"NtXagAClV"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
											}}
										>
											{"Page Not Found"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-q4fgxw"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"VTj9_gBrI"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-kwq25o"}
											data-styles-preset={"ubCiarRXL"}
										>
											{"404"}
										</motion.h1>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-13l33ts"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"GnBHEXkpw"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-qyurt7"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"wNnZOY7Y0"}
									style={{
										"--extracted-1w1cjl5":
											"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-15z4rdv"}
											data-styles-preset={"U1mraOJjt"}
											style={{
												"--framer-text-color":
													"var(--extracted-1w1cjl5, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
											}}
										>
											{"Oops! It looks like you\u2019re lost."}
										</motion.h6>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-16bhaei"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"McJgkL7Mu"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-144gy8o"}
											data-styles-preset={"qA7GDH1GX"}
										>
											{
												"The page you\u2019re looking for might have been moved, renamed, or doesn\u2019t exist. But don\u2019t worry, let\u2019s get you back on track."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-c0qqw1"}
								data-framer-name={"Action"}
								layoutDependency={layoutDependency}
								layoutId={"Pc5T8BgMl"}
							>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider height={33}>
											<SmartComponentScopedContainer
												className={"framer-rzqv3k-container"}
												layoutDependency={layoutDependency}
												layoutId={"ZOk7yTNqx-container"}
												nodeId={"ZOk7yTNqx"}
												rendersWithMotion={true}
												scopeId={"ejiZj1Tjq"}
											>
												{_jsx(stdin_default, {
													A1mdPRDCS: "Go Back to Home",
													height: "100%",
													id: "ZOk7yTNqx",
													KKQ6Z0zNX: resolvedLinks[0],
													layoutId: "ZOk7yTNqx",
													variant: "GQY9EfGY4",
													width: "100%",
													...addPropertyOverrides(
														{
															fNHbFKi0D: {
																KKQ6Z0zNX: resolvedLinks[1],
															},
															HYpK9aD2Y: {
																KKQ6Z0zNX: resolvedLinks[2],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "wwtpvR9H7",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "wwtpvR9H7",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "wwtpvR9H7",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks1) => (
										<ComponentViewportProvider height={33}>
											<SmartComponentScopedContainer
												className={"framer-dg4kzw-container"}
												layoutDependency={layoutDependency}
												layoutId={"ynV4jZart-container"}
												nodeId={"ynV4jZart"}
												rendersWithMotion={true}
												scopeId={"ejiZj1Tjq"}
											>
												{_jsx(stdin_default, {
													A1mdPRDCS: "Explore Our Projects",
													height: "100%",
													id: "ynV4jZart",
													KKQ6Z0zNX: resolvedLinks1[0],
													layoutId: "ynV4jZart",
													variant: "GQY9EfGY4",
													width: "100%",
													...addPropertyOverrides(
														{
															fNHbFKi0D: {
																KKQ6Z0zNX: resolvedLinks1[1],
															},
															HYpK9aD2Y: {
																KKQ6Z0zNX: resolvedLinks1[2],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "WOrYUhfBH",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "WOrYUhfBH",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "WOrYUhfBH",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks2) => (
										<ComponentViewportProvider height={33}>
											<SmartComponentScopedContainer
												className={"framer-1y5mg10-container"}
												layoutDependency={layoutDependency}
												layoutId={"SQze4dL4v-container"}
												nodeId={"SQze4dL4v"}
												rendersWithMotion={true}
												scopeId={"ejiZj1Tjq"}
											>
												{_jsx(stdin_default, {
													A1mdPRDCS: "Contact Us",
													height: "100%",
													id: "SQze4dL4v",
													KKQ6Z0zNX: resolvedLinks2[0],
													layoutId: "SQze4dL4v",
													variant: "GQY9EfGY4",
													width: "100%",
													...addPropertyOverrides(
														{
															fNHbFKi0D: {
																KKQ6Z0zNX: resolvedLinks2[1],
															},
															HYpK9aD2Y: {
																KKQ6Z0zNX: resolvedLinks2[2],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UiAQ7.framer-1a0lgcg, .framer-UiAQ7 .framer-1a0lgcg { display: block; }",
	".framer-UiAQ7.framer-14xa0io { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 800px; justify-content: center; overflow: hidden; padding: 50px; position: relative; width: 1200px; }",
	".framer-UiAQ7 .framer-1foqma2 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-UiAQ7 .framer-37xrg3, .framer-UiAQ7 .framer-13l33ts { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-UiAQ7 .framer-mrrxzt, .framer-UiAQ7 .framer-q4fgxw, .framer-UiAQ7 .framer-qyurt7, .framer-UiAQ7 .framer-16bhaei { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-UiAQ7 .framer-c0qqw1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-UiAQ7 .framer-rzqv3k-container, .framer-UiAQ7 .framer-dg4kzw-container, .framer-UiAQ7 .framer-1y5mg10-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-UiAQ7.framer-v-176eg9w.framer-14xa0io { height: 1080px; padding: 40px 30px 80px 30px; width: 810px; }",
	".framer-UiAQ7.framer-v-176eg9w .framer-1foqma2 { gap: 56px; }",
	".framer-UiAQ7.framer-v-176eg9w .framer-37xrg3, .framer-UiAQ7.framer-v-176eg9w .framer-13l33ts { max-width: 550px; }",
	".framer-UiAQ7.framer-v-r85405.framer-14xa0io { height: 844px; padding: 30px 16px 60px 16px; width: 200px; }",
	...css,
	...css4,
	...css3,
	...css2,
];
var FramerejiZj1Tjq = withCSS(Component, css5, "framer-UiAQ7");
var stdin_default2 = FramerejiZj1Tjq;
FramerejiZj1Tjq.displayName = "404";
FramerejiZj1Tjq.defaultProps = {
	height: 800,
	width: 1200,
};
addPropertyControls(FramerejiZj1Tjq, {
	variant: {
		options: ["irTWLuvdP", "fNHbFKi0D", "HYpK9aD2Y"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerejiZj1Tjq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonPrimaryFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:404
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HYpK9aD2Y",
	md: "fNHbFKi0D",
	xl: "irTWLuvdP",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Framer404FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var __default = ComponentWithRoot;
export { __default as default };
