// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-FUFM4S6K.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EQ6EOYNA.js";
import "./chunks/chunk-FYMJT4D6.js";
import { className, css, fonts } from "./chunks/chunk-N4SVWGDY.js";
import "./chunks/chunk-2RKPPYFD.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:about1
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/ABOUT1-vNYf.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MiscValueFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var cycleOrder = ["WS7RJzod5", "Pv9LSNDec", "NPFQkLyIf"];
var serializationHash = "framer-hlFAp";
var variantClassNames = {
	NPFQkLyIf: "framer-v-147fndx",
	Pv9LSNDec: "framer-v-1uw7doz",
	WS7RJzod5: "framer-v-jb4z33",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	filter: "blur(7px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	damping: 58,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0,
	threshold: 0,
	tokenization: "word",
	transition: transition2,
	trigger: "onInView",
	type: "appear",
};
var transition3 = {
	damping: 58,
	delay: 0.65,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 7,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "WS7RJzod5",
	Phone: "NPFQkLyIf",
	Tablet: "Pv9LSNDec",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "WS7RJzod5",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "WS7RJzod5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-jb4z33",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"WS7RJzod5"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								NPFQkLyIf: {
									"data-framer-name": "Phone",
								},
								Pv9LSNDec: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 800) -
											0 -
											(Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
												158 +
												0)) /
											2 +
											0 +
											0),
								),
								pixelHeight: 3e3,
								pixelWidth: 4500,
								positionX: "center",
								positionY: "bottom",
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg",
								srcSet:
									"https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg 4500w",
							}}
							className={"framer-1hoxk24"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"stQ6iCpM0"}
							{...addPropertyOverrides(
								{
									NPFQkLyIf: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 701.2) /
														2 +
														0 +
														0),
											),
											pixelHeight: 3e3,
											pixelWidth: 4500,
											positionX: "center",
											positionY: "bottom",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg",
											srcSet:
												"https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg 4500w",
										},
									},
									Pv9LSNDec: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 864) -
														0 -
														(Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
															138 +
															0)) /
														2 +
														0 +
														0),
											),
											pixelHeight: 3e3,
											pixelWidth: 4500,
											positionX: "center",
											positionY: "bottom",
											sizes: componentViewport?.width || "100vw",
											src: "https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg",
											srcSet:
												"https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/RjwywXAWDy5A9NeJr8uAZuQeIHM.jpg 4500w",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-3qf1o1"}
								data-framer-name={"Cover"}
								layoutDependency={layoutDependency}
								layoutId={"cefkMwv1y"}
								style={{
									backgroundColor:
										"var(--token-5770d3e9-9831-4835-877a-d46a51cd6e02, rgba(0, 0, 0, 0.6))",
								}}
							>
								<motion.div
									className={"framer-sxi4ii"}
									data-framer-name={"Inner"}
									layoutDependency={layoutDependency}
									layoutId={"gMy2l6_79"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-g8twee"}
										effect={textEffect}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"k8juoTpYu"}
										style={{
											"--extracted-gdpscs":
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h1
												className={"framer-styles-preset-1n41l9y"}
												data-styles-preset={"YMmsPodJ4"}
												style={{
													"--framer-text-color":
														"var(--extracted-gdpscs, var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255)))",
												}}
											>
												{"About Studios."}
											</motion.h1>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-evvuoq"}
										effect={textEffect}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SOVZyZWqI"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-144gy8o"}
												data-styles-preset={"qA7GDH1GX"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255)))",
												}}
											>
												{
													"Whether designing homes, commercial spaces, or urban landscapes, we focus on crafting environments that enrich lives and stand the test of time."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</Image>
						<motion.div
							className={"framer-ryt4pd"}
							data-framer-name={"Value"}
							layoutDependency={layoutDependency}
							layoutId={"avDcaR10D"}
							style={{
								backgroundColor:
									"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
							}}
						>
							<motion.div
								className={"framer-1affyjf"}
								data-framer-name={"Inner"}
								layoutDependency={layoutDependency}
								layoutId={"udXJSxvyO"}
							>
								<ComponentViewportProvider
									height={58}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 96px) / 3, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 800) -
											0 -
											(Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
												158 +
												0)) /
											2 +
											Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
											0) +
										50 +
										0
									}
									{...addPropertyOverrides(
										{
											NPFQkLyIf: {
												width: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 701.2) /
														2 +
														403.2 +
														0) +
													30 +
													0 +
													0,
											},
											Pv9LSNDec: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) - 48px) / 3, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 864) -
														0 -
														(Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
															138 +
															0)) /
														2 +
														Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
														0) +
													40 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation1}
										className={"framer-1r2om7d-container"}
										data-framer-appear-id={"1r2om7d"}
										initial={animation2}
										layoutDependency={layoutDependency}
										layoutId={"CfbgRm8Pf-container"}
										nodeId={"CfbgRm8Pf"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"buKqTwEME"}
									>
										{_jsx(stdin_default, {
											auZOkYfuS: "Our Vision",
											Ceh50lUWz:
												"To redefine modern architecture by creating inspiring, sustainable, and functional spaces that shape the future.",
											height: "100%",
											id: "CfbgRm8Pf",
											layoutId: "CfbgRm8Pf",
											style: {
												width: "100%",
											},
											variant: "zKzmz0fcL",
											width: "100%",
											yY4Dsu0By:
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={58}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 96px) / 3, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 800) -
											0 -
											(Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
												158 +
												0)) /
											2 +
											Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
											0) +
										50 +
										0
									}
									{...addPropertyOverrides(
										{
											NPFQkLyIf: {
												width: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 701.2) /
														2 +
														403.2 +
														0) +
													30 +
													0 +
													90,
											},
											Pv9LSNDec: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) - 48px) / 3, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 864) -
														0 -
														(Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
															138 +
															0)) /
														2 +
														Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
														0) +
													40 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation1}
										className={"framer-adf07a-container"}
										data-framer-appear-id={"adf07a"}
										initial={animation2}
										layoutDependency={layoutDependency}
										layoutId={"pKtRzwgm5-container"}
										nodeId={"pKtRzwgm5"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"buKqTwEME"}
									>
										{_jsx(stdin_default, {
											auZOkYfuS: "Our Mission",
											Ceh50lUWz:
												"To deliver innovative, client-focused architectural solutions that blend aesthetics, efficiency, and environmental responsibility.",
											height: "100%",
											id: "pKtRzwgm5",
											layoutId: "pKtRzwgm5",
											style: {
												width: "100%",
											},
											variant: "zKzmz0fcL",
											width: "100%",
											yY4Dsu0By:
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={58}
									width={`max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 96px) / 3, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 800) -
											0 -
											(Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
												158 +
												0)) /
											2 +
											Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 158) / 1,
											) *
												1 +
											0) +
										50 +
										0
									}
									{...addPropertyOverrides(
										{
											NPFQkLyIf: {
												width: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 701.2) /
														2 +
														403.2 +
														0) +
													30 +
													0 +
													180,
											},
											Pv9LSNDec: {
												width: `max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) - 48px) / 3, 1px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 864) -
														0 -
														(Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
															138 +
															0)) /
														2 +
														Math.max(
															0,
															((componentViewport?.height || 864) - 0 - 138) /
																1,
														) *
															1 +
														0) +
													40 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation1}
										className={"framer-wsttm0-container"}
										data-framer-appear-id={"wsttm0"}
										initial={animation2}
										layoutDependency={layoutDependency}
										layoutId={"G7cMTp6F2-container"}
										nodeId={"G7cMTp6F2"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"buKqTwEME"}
									>
										{_jsx(stdin_default, {
											auZOkYfuS: "Core Value",
											Ceh50lUWz:
												"To uphold innovation, sustainability, excellence, and collaboration in every project, ensuring timeless design and meaningful impact.",
											height: "100%",
											id: "G7cMTp6F2",
											layoutId: "G7cMTp6F2",
											style: {
												width: "100%",
											},
											variant: "zKzmz0fcL",
											width: "100%",
											yY4Dsu0By:
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-hlFAp.framer-enx5mq, .framer-hlFAp .framer-enx5mq { display: block; }",
	".framer-hlFAp.framer-jb4z33 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 800px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-hlFAp .framer-1hoxk24 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-hlFAp .framer-3qf1o1 { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: hidden; padding: 50px; position: relative; width: 1px; }",
	".framer-hlFAp .framer-sxi4ii { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-hlFAp .framer-g8twee, .framer-hlFAp .framer-evvuoq { flex: 1 0 0px; height: auto; max-width: 350px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-hlFAp .framer-ryt4pd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 50px; position: relative; width: 100%; }",
	".framer-hlFAp .framer-1affyjf { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-hlFAp .framer-1r2om7d-container, .framer-hlFAp .framer-adf07a-container, .framer-hlFAp .framer-wsttm0-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-hlFAp.framer-v-1uw7doz.framer-jb4z33 { height: 864px; width: 810px; }",
	".framer-hlFAp.framer-v-1uw7doz .framer-3qf1o1, .framer-hlFAp.framer-v-1uw7doz .framer-ryt4pd { padding: 40px 30px 40px 30px; }",
	".framer-hlFAp.framer-v-1uw7doz .framer-g8twee { max-width: 300px; }",
	".framer-hlFAp.framer-v-1uw7doz .framer-1affyjf { gap: 24px; }",
	".framer-hlFAp.framer-v-147fndx.framer-jb4z33 { height: 200px; width: 200px; }",
	".framer-hlFAp.framer-v-147fndx .framer-1hoxk24 { flex: none; height: min-content; }",
	".framer-hlFAp.framer-v-147fndx .framer-3qf1o1 { height: min-content; padding: 150px 16px 50px 16px; }",
	".framer-hlFAp.framer-v-147fndx .framer-sxi4ii { flex-direction: column; gap: 24px; justify-content: center; }",
	".framer-hlFAp.framer-v-147fndx .framer-g8twee, .framer-hlFAp.framer-v-147fndx .framer-evvuoq { flex: none; max-width: unset; width: 100%; }",
	".framer-hlFAp.framer-v-147fndx .framer-ryt4pd { padding: 30px 16px 30px 16px; }",
	".framer-hlFAp.framer-v-147fndx .framer-1affyjf { flex-direction: column; gap: 32px; }",
	".framer-hlFAp.framer-v-147fndx .framer-1r2om7d-container, .framer-hlFAp.framer-v-147fndx .framer-adf07a-container, .framer-hlFAp.framer-v-147fndx .framer-wsttm0-container { flex: none; width: 100%; }",
	...css2,
	...css,
];
var FramerbuKqTwEME = withCSS(Component, css3, "framer-hlFAp");
var stdin_default2 = FramerbuKqTwEME;
FramerbuKqTwEME.displayName = "ABOUT1";
FramerbuKqTwEME.defaultProps = {
	height: 800,
	width: 1200,
};
addPropertyControls(FramerbuKqTwEME, {
	variant: {
		options: ["WS7RJzod5", "Pv9LSNDec", "NPFQkLyIf"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerbuKqTwEME,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MiscValueFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:about1
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "NPFQkLyIf",
	md: "Pv9LSNDec",
	xl: "WS7RJzod5",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders About1FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var about1_default = ComponentWithRoot;
export { about1_default as default };
