// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Slideshow } from "./chunks/chunk-QSCDEF5D.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-RZ6XIZ35.js";
import { className, css, fonts } from "./chunks/chunk-MBDBQ6CG.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-2RKPPYFD.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6TWF3UWX.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:about3
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/ABOUT3-e9yP.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/gMutOuh3fvmdxs3Q8QQM/JyeG10cz8EDQL1dKiRf4/ZQuubFkEq.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getPropertyControls,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/KaYJjdolGJA0R3YlCKV4/IIcaWOUrNoCFf0oATysP/JKpQaMNzW.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["BCZa_o_jN", "jhlxEmfjh", "VaSi0S1Lm"];
var serializationHash = "framer-xobV0";
var variantClassNames = {
	BCZa_o_jN: "framer-v-io0ers",
	jhlxEmfjh: "framer-v-bt89wc",
	VaSi0S1Lm: "framer-v-1n4ep66",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "BCZa_o_jN",
	Phone: "VaSi0S1Lm",
	Tablet: "jhlxEmfjh",
};
var getProps = ({
	description,
	height,
	id,
	image,
	number,
	title,
	width,
	...props
}) => {
	return {
		...props,
		EG9LwoFBz: number ?? props.EG9LwoFBz ?? "01",
		o7uskqZ4c:
			description ??
			props.o7uskqZ4c ??
			"We believe architecture should push boundaries, blending creativity with cutting-edge technology to create spaces that are both aesthetically striking and highly functional. Our designs embrace bold concepts, meticulous craftsmanship, and future-ready solutions that redefine the way people experience their surroundings.",
		QnOoSZgEx: image ??
			props.QnOoSZgEx ?? {
				alt: "",
				src: "https://framerusercontent.com/images/4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg 4480w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "BCZa_o_jN",
		wyJ6FzVtr: title ?? props.wyJ6FzVtr ?? "Innovative Design",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		EG9LwoFBz,
		wyJ6FzVtr,
		o7uskqZ4c,
		QnOoSZgEx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "BCZa_o_jN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className4];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-io0ers",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"BCZa_o_jN"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								jhlxEmfjh: {
									"data-framer-name": "Tablet",
								},
								VaSi0S1Lm: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-19ccdqf"}
							data-framer-name={"Details"}
							layoutDependency={layoutDependency}
							layoutId={"geli0Y1KD"}
						>
							<motion.div
								className={"framer-1oaivcd"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"f89bqqIm9"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-go59rg"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"t2dmY_0QJ"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={EG9LwoFBz}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-144gy8o"}
											data-styles-preset={"qA7GDH1GX"}
										>
											{"01"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qxmr5x"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"jBFRzQ58U"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={wyJ6FzVtr}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1u1gid8"}
											data-styles-preset={"dWQejjq7v"}
										>
											{"Innovative Design"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-45p05w"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"c2ujP1hNj"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={o7uskqZ4c}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-144gy8o"}
										data-styles-preset={"qA7GDH1GX"}
									>
										{
											"We believe architecture should push boundaries, blending creativity with cutting-edge technology to create spaces that are both aesthetically striking and highly functional. Our designs embrace bold concepts, meticulous craftsmanship, and future-ready solutions that redefine the way people experience their surroundings."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 697,
								intrinsicWidth: 1020,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										0 +
										((componentViewport?.height || 400) -
											48 -
											((componentViewport?.height || 400) - 48) * 1),
								),
								pixelHeight: 6720,
								pixelWidth: 4480,
								sizes: `max((${componentViewport?.width || "100vw"} - 80px) / 2, 1px)`,
								...toResponsiveImage(QnOoSZgEx),
							}}
							className={"framer-1rbwnt9"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"yN8_uGVbO"}
							{...addPropertyOverrides(
								{
									jhlxEmfjh: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 697,
											intrinsicWidth: 1020,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													((componentViewport?.height || 380) -
														32 -
														((componentViewport?.height || 380) - 32) * 1),
											),
											pixelHeight: 6720,
											pixelWidth: 4480,
											sizes: `max((${componentViewport?.width || "100vw"} - 48px) / 2, 1px)`,
											...toResponsiveImage(QnOoSZgEx),
										},
									},
									VaSi0S1Lm: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 697,
											intrinsicWidth: 1020,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 600) -
														32 -
														(169.6 +
															Math.max(
																0,
																((componentViewport?.height || 600) -
																	32 -
																	193.6) /
																	1,
															) *
																1 +
															24)) /
														2 +
														169.6 +
														24),
											),
											pixelHeight: 6720,
											pixelWidth: 4480,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(QnOoSZgEx),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xobV0.framer-ka66gg, .framer-xobV0 .framer-ka66gg { display: block; }",
	".framer-xobV0.framer-io0ers { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: 400px; justify-content: center; overflow: hidden; padding: 0px 0px 48px 0px; position: relative; width: 1100px; }",
	".framer-xobV0 .framer-19ccdqf { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-xobV0 .framer-1oaivcd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xobV0 .framer-go59rg { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-xobV0 .framer-1qxmr5x { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-xobV0 .framer-45p05w { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-xobV0 .framer-1rbwnt9 { flex: 1 0 0px; height: 100%; overflow: visible; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xobV0.framer-io0ers, .framer-xobV0 .framer-19ccdqf, .framer-xobV0 .framer-1oaivcd { gap: 0px; } .framer-xobV0.framer-io0ers > * { margin: 0px; margin-left: calc(80px / 2); margin-right: calc(80px / 2); } .framer-xobV0.framer-io0ers > :first-child, .framer-xobV0 .framer-1oaivcd > :first-child { margin-left: 0px; } .framer-xobV0.framer-io0ers > :last-child, .framer-xobV0 .framer-1oaivcd > :last-child { margin-right: 0px; } .framer-xobV0 .framer-19ccdqf > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-xobV0 .framer-19ccdqf > :first-child { margin-top: 0px; } .framer-xobV0 .framer-19ccdqf > :last-child { margin-bottom: 0px; } .framer-xobV0 .framer-1oaivcd > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } }",
	".framer-xobV0.framer-v-bt89wc.framer-io0ers { gap: 48px; height: 380px; padding: 0px 0px 32px 0px; width: 750px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xobV0.framer-v-bt89wc.framer-io0ers { gap: 0px; } .framer-xobV0.framer-v-bt89wc.framer-io0ers > * { margin: 0px; margin-left: calc(48px / 2); margin-right: calc(48px / 2); } .framer-xobV0.framer-v-bt89wc.framer-io0ers > :first-child { margin-left: 0px; } .framer-xobV0.framer-v-bt89wc.framer-io0ers > :last-child { margin-right: 0px; } }",
	".framer-xobV0.framer-v-1n4ep66.framer-io0ers { flex-direction: column; gap: 24px; height: 600px; padding: 0px 0px 32px 0px; width: 358px; }",
	".framer-xobV0.framer-v-1n4ep66 .framer-19ccdqf { flex: none; width: 100%; }",
	".framer-xobV0.framer-v-1n4ep66 .framer-1rbwnt9 { height: 1px; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xobV0.framer-v-1n4ep66.framer-io0ers { gap: 0px; } .framer-xobV0.framer-v-1n4ep66.framer-io0ers > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-xobV0.framer-v-1n4ep66.framer-io0ers > :first-child { margin-top: 0px; } .framer-xobV0.framer-v-1n4ep66.framer-io0ers > :last-child { margin-bottom: 0px; } }",
	...css3,
	...css4,
	'.framer-xobV0[data-border="true"]::after, .framer-xobV0 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerJKpQaMNzW = withCSS(Component, css5, "framer-xobV0");
var stdin_default = FramerJKpQaMNzW;
FramerJKpQaMNzW.displayName = "Card/Approach";
FramerJKpQaMNzW.defaultProps = {
	height: 400,
	width: 1100,
};
addPropertyControls(FramerJKpQaMNzW, {
	variant: {
		options: ["BCZa_o_jN", "jhlxEmfjh", "VaSi0S1Lm"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	EG9LwoFBz: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	wyJ6FzVtr: {
		defaultValue: "Innovative Design",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	o7uskqZ4c: {
		defaultValue:
			"We believe architecture should push boundaries, blending creativity with cutting-edge technology to create spaces that are both aesthetically striking and highly functional. Our designs embrace bold concepts, meticulous craftsmanship, and future-ready solutions that redefine the way people experience their surroundings.",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	QnOoSZgEx: {
		__defaultAssetReference:
			"data:framer/asset-reference,4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg?originalFilename=photo-1551038247-3d9af20df552%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwyfHxhcmNoaXRlY3xlbnwwfHx8fDE3NDIzMjU2MzB8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,4Dt1pOHDnS0C1WNX7a9Ma9Vl57I.jpg?originalFilename=photo-1551038247-3d9af20df552%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwyfHxhcmNoaXRlY3xlbnwwfHx8fDE3NDIzMjU2MzB8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerJKpQaMNzW,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/gMutOuh3fvmdxs3Q8QQM/JyeG10cz8EDQL1dKiRf4/ZQuubFkEq.js
var CardApproachFonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var CardApproachControls = getPropertyControls(stdin_default);
var serializationHash2 = "framer-Q3lN1";
var variantClassNames2 = {
	Qkd64jGfv: "framer-v-1wux9q5",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	Desktop: "BCZa_o_jN",
	Phone: "VaSi0S1Lm",
	Tablet: "jhlxEmfjh",
};
var getProps2 = ({
	description01,
	description02,
	description03,
	description04,
	height,
	id,
	image01,
	image02,
	image03,
	image04,
	size,
	title01,
	title02,
	title03,
	title04,
	width,
	...props
}) => {
	return {
		...props,
		AI8ustKAD: title04 ?? props.AI8ustKAD ?? "Adaptability",
		en0H2GSvz: image03 ??
			props.en0H2GSvz ?? {
				pixelHeight: 4167,
				pixelWidth: 3125,
				src: "https://framerusercontent.com/images/u6fApwxZkuyHfLmShbrytbQcmw.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/u6fApwxZkuyHfLmShbrytbQcmw.jpg?scale-down-to=1024 767w,https://framerusercontent.com/images/u6fApwxZkuyHfLmShbrytbQcmw.jpg?scale-down-to=2048 1535w,https://framerusercontent.com/images/u6fApwxZkuyHfLmShbrytbQcmw.jpg?scale-down-to=4096 3071w,https://framerusercontent.com/images/u6fApwxZkuyHfLmShbrytbQcmw.jpg 3125w",
			},
		hSeouvabk: image01 ??
			props.hSeouvabk ?? {
				pixelHeight: 3456,
				pixelWidth: 5184,
				src: "https://framerusercontent.com/images/gLuHtmqVtrk9h3ST7lAr89YVY.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/gLuHtmqVtrk9h3ST7lAr89YVY.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/gLuHtmqVtrk9h3ST7lAr89YVY.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/gLuHtmqVtrk9h3ST7lAr89YVY.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/gLuHtmqVtrk9h3ST7lAr89YVY.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/gLuHtmqVtrk9h3ST7lAr89YVY.jpg 5184w",
			},
		MTvFaXRgp: title01 ?? props.MTvFaXRgp ?? "Innovative Design",
		QNMC8psw8:
			description04 ??
			props.QNMC8psw8 ??
			"The world is constantly evolving, and so is architecture. We embrace flexibility in design, allowing spaces to adapt to changing needs, technologies, and lifestyles. Whether it\u2019s reconfigurable layouts, modular structures, or innovative materials, we ensure that our projects remain relevant and future-proof.",
		SyvApxOld:
			description01 ??
			props.SyvApxOld ??
			"We believe architecture should push boundaries, blending creativity with cutting-edge technology to create spaces that are both aesthetically striking and highly functional. Our designs embrace bold concepts, meticulous craftsmanship, and future-ready solutions that redefine the way people experience their surroundings.",
		tdtl2OItr: title02 ?? props.tdtl2OItr ?? "Client-Centric Approach",
		UGN1LCX14: image02 ??
			props.UGN1LCX14 ?? {
				pixelHeight: 3e3,
				pixelWidth: 4e3,
				src: "https://framerusercontent.com/images/bSQ1UciLKs4a6y4oSUz99A.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/bSQ1UciLKs4a6y4oSUz99A.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/bSQ1UciLKs4a6y4oSUz99A.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/bSQ1UciLKs4a6y4oSUz99A.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/bSQ1UciLKs4a6y4oSUz99A.jpg 4000w",
			},
		uMNAV6X96:
			description03 ??
			props.uMNAV6X96 ??
			"We integrate eco-conscious strategies into every stage of design and construction, prioritizing energy efficiency, sustainable materials, and minimal environmental impact. By focusing on longevity and responsible design choices, we create buildings that harmonize with their surroundings and stand the test of time.",
		XZbNx08D5:
			description02 ??
			props.XZbNx08D5 ??
			"Every project starts with understanding our clients\u2019 vision, needs, and aspirations. We collaborate closely throughout the design process, ensuring that every detail aligns with their goals. Our tailored approach guarantees that each space is a true reflection of its users, balancing personal style with architectural excellence.",
		YDyPo_uqq:
			humanReadableEnumMap[size] ?? size ?? props.YDyPo_uqq ?? "BCZa_o_jN",
		ZkLO10pL9: image04 ??
			props.ZkLO10pL9 ?? {
				pixelHeight: 4e3,
				pixelWidth: 6e3,
				src: "https://framerusercontent.com/images/LDjYU5dGcokAn2WS2qMzhYLofY.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/LDjYU5dGcokAn2WS2qMzhYLofY.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/LDjYU5dGcokAn2WS2qMzhYLofY.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/LDjYU5dGcokAn2WS2qMzhYLofY.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/LDjYU5dGcokAn2WS2qMzhYLofY.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/LDjYU5dGcokAn2WS2qMzhYLofY.jpg 6000w",
			},
		ZrswWKKgU: title03 ?? props.ZrswWKKgU ?? "Sustainable Practices",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		YDyPo_uqq,
		MTvFaXRgp,
		SyvApxOld,
		hSeouvabk,
		tdtl2OItr,
		XZbNx08D5,
		UGN1LCX14,
		ZrswWKKgU,
		uMNAV6X96,
		en0H2GSvz,
		AI8ustKAD,
		QNMC8psw8,
		ZkLO10pL9,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "Qkd64jGfv",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1wux9q5",
							className5,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"Qkd64jGfv"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-ip94mq-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"Rc5lPfHLb-container"}
								nodeId={"Rc5lPfHLb"}
								rendersWithMotion={true}
								scopeId={"ZQuubFkEq"}
							>
								<Slideshow
									alignment={"center"}
									arrowOptions={{
										arrowFill:
											"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
										arrowGap: 10,
										arrowPadding: 20,
										arrowPaddingBottom: -50,
										arrowPaddingLeft: 0,
										arrowPaddingRight: 0,
										arrowPaddingTop: 0,
										arrowPosition: "bottom-left",
										arrowRadius: 100,
										arrowShouldFadeIn: false,
										arrowShouldSpace: false,
										arrowSize: 28,
										showMouseControls: true,
									}}
									autoPlayControl={false}
									borderRadius={0}
									direction={"left"}
									dragControl={false}
									effectsOptions={{
										effectsHover: true,
										effectsOpacity: 1,
										effectsPerspective: 1200,
										effectsRotate: 0,
										effectsScale: 1,
										playOffscreen: false,
									}}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={10}
									height={"100%"}
									id={"Rc5lPfHLb"}
									intervalControl={10}
									itemAmount={1}
									layoutId={"Rc5lPfHLb"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									progressOptions={{
										dotsActiveOpacity: 1,
										dotsBackground: "rgba(0, 0, 0, 0.2)",
										dotsBlur: 0,
										dotsFill:
											"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
										dotsGap: 10,
										dotsInset: 10,
										dotSize: 10,
										dotsOpacity: 0.5,
										dotsPadding: 10,
										dotsRadius: 50,
										showProgressDots: false,
									}}
									slots={[
										<ComponentViewportProvider height={400} width={"1100px"}>
											<SmartComponentScopedContainer
												className={"framer-131sc83-container"}
												data-framer-name={"01"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"KpQ2MDMuy-container"}
												name={"01"}
												nodeId={"KpQ2MDMuy"}
												rendersWithMotion={true}
												scopeId={"ZQuubFkEq"}
											>
												{_jsx2(stdin_default, {
													EG9LwoFBz: "01",
													height: "100%",
													id: "KpQ2MDMuy",
													layoutId: "KpQ2MDMuy",
													name: "01",
													o7uskqZ4c: SyvApxOld,
													QnOoSZgEx: toResponsiveImage2(hSeouvabk),
													style: {
														width: "100%",
													},
													variant: YDyPo_uqq,
													width: "100%",
													wyJ6FzVtr: MTvFaXRgp,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={400} width={"1100px"}>
											<SmartComponentScopedContainer
												className={"framer-11c1ia-container"}
												data-framer-name={"02"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"sMC28vHMK-container"}
												name={"02"}
												nodeId={"sMC28vHMK"}
												rendersWithMotion={true}
												scopeId={"ZQuubFkEq"}
											>
												{_jsx2(stdin_default, {
													EG9LwoFBz: "02",
													height: "100%",
													id: "sMC28vHMK",
													layoutId: "sMC28vHMK",
													name: "02",
													o7uskqZ4c: XZbNx08D5,
													QnOoSZgEx: toResponsiveImage2(UGN1LCX14),
													style: {
														width: "100%",
													},
													variant: YDyPo_uqq,
													width: "100%",
													wyJ6FzVtr: tdtl2OItr,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={400} width={"1100px"}>
											<SmartComponentScopedContainer
												className={"framer-11jcsz5-container"}
												data-framer-name={"03"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"aXyZd9Aef-container"}
												name={"03"}
												nodeId={"aXyZd9Aef"}
												rendersWithMotion={true}
												scopeId={"ZQuubFkEq"}
											>
												{_jsx2(stdin_default, {
													EG9LwoFBz: "03",
													height: "100%",
													id: "aXyZd9Aef",
													layoutId: "aXyZd9Aef",
													name: "03",
													o7uskqZ4c: uMNAV6X96,
													QnOoSZgEx: toResponsiveImage2(en0H2GSvz),
													style: {
														width: "100%",
													},
													variant: YDyPo_uqq,
													width: "100%",
													wyJ6FzVtr: ZrswWKKgU,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={400} width={"1100px"}>
											<SmartComponentScopedContainer
												className={"framer-2tia1a-container"}
												data-framer-name={"04"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"hqHXbr6TX-container"}
												name={"04"}
												nodeId={"hqHXbr6TX"}
												rendersWithMotion={true}
												scopeId={"ZQuubFkEq"}
											>
												{_jsx2(stdin_default, {
													EG9LwoFBz: "04",
													height: "100%",
													id: "hqHXbr6TX",
													layoutId: "hqHXbr6TX",
													name: "04",
													o7uskqZ4c: QNMC8psw8,
													QnOoSZgEx: toResponsiveImage2(ZkLO10pL9),
													style: {
														width: "100%",
													},
													variant: YDyPo_uqq,
													width: "100%",
													wyJ6FzVtr: AI8ustKAD,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									startFrom={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									transitionControl={{
										damping: 40,
										delay: 0,
										mass: 1,
										stiffness: 200,
										type: "spring",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Q3lN1.framer-1rg1gi8, .framer-Q3lN1 .framer-1rg1gi8 { display: block; }",
	".framer-Q3lN1.framer-1wux9q5 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1100px; }",
	".framer-Q3lN1 .framer-ip94mq-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; }",
	".framer-Q3lN1 .framer-131sc83-container, .framer-Q3lN1 .framer-11c1ia-container, .framer-Q3lN1 .framer-11jcsz5-container, .framer-Q3lN1 .framer-2tia1a-container { height: auto; position: relative; width: 1100px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Q3lN1.framer-1wux9q5 { gap: 0px; } .framer-Q3lN1.framer-1wux9q5 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-Q3lN1.framer-1wux9q5 > :first-child { margin-top: 0px; } .framer-Q3lN1.framer-1wux9q5 > :last-child { margin-bottom: 0px; } }",
];
var FramerZQuubFkEq = withCSS2(Component2, css6, "framer-Q3lN1");
var stdin_default2 = FramerZQuubFkEq;
FramerZQuubFkEq.displayName = "Slideshow/Approach";
FramerZQuubFkEq.defaultProps = {
	height: 400,
	width: 1100,
};
addPropertyControls2(FramerZQuubFkEq, {
	YDyPo_uqq: CardApproachControls?.["variant"] && {
		...CardApproachControls["variant"],
		defaultValue: "BCZa_o_jN",
		description: void 0,
		hidden: void 0,
		title: "Size",
	},
	MTvFaXRgp: {
		defaultValue: "Innovative Design",
		displayTextArea: false,
		title: "Title 01",
		type: ControlType2.String,
	},
	SyvApxOld: {
		defaultValue:
			"We believe architecture should push boundaries, blending creativity with cutting-edge technology to create spaces that are both aesthetically striking and highly functional. Our designs embrace bold concepts, meticulous craftsmanship, and future-ready solutions that redefine the way people experience their surroundings.",
		displayTextArea: false,
		title: "Description 01",
		type: ControlType2.String,
	},
	hSeouvabk: {
		__defaultAssetReference:
			"data:framer/asset-reference,gLuHtmqVtrk9h3ST7lAr89YVY.jpg?originalFilename=photo-1434030216411-0b793f4b4173%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw4fHxhcmNoaXRlY3QlMjBkZXNpZ258ZW58MHx8fHwxNzQyMzkwODYwfDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 01",
		type: ControlType2.ResponsiveImage,
	},
	tdtl2OItr: {
		defaultValue: "Client-Centric Approach",
		displayTextArea: false,
		title: "Title 02",
		type: ControlType2.String,
	},
	XZbNx08D5: {
		defaultValue:
			"Every project starts with understanding our clients\u2019 vision, needs, and aspirations. We collaborate closely throughout the design process, ensuring that every detail aligns with their goals. Our tailored approach guarantees that each space is a true reflection of its users, balancing personal style with architectural excellence.",
		displayTextArea: false,
		title: "Description 02",
		type: ControlType2.String,
	},
	UGN1LCX14: {
		__defaultAssetReference:
			"data:framer/asset-reference,bSQ1UciLKs4a6y4oSUz99A.jpg?originalFilename=photo-1591588582259-e675bd2e6088%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMXx8Y29uc3RydWN0aW9ufGVufDB8fHx8MTc0MjM5MDk4NHww%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 02",
		type: ControlType2.ResponsiveImage,
	},
	ZrswWKKgU: {
		defaultValue: "Sustainable Practices",
		displayTextArea: false,
		title: "Title 03",
		type: ControlType2.String,
	},
	uMNAV6X96: {
		defaultValue:
			"We integrate eco-conscious strategies into every stage of design and construction, prioritizing energy efficiency, sustainable materials, and minimal environmental impact. By focusing on longevity and responsible design choices, we create buildings that harmonize with their surroundings and stand the test of time.",
		displayTextArea: false,
		title: "Description 03",
		type: ControlType2.String,
	},
	en0H2GSvz: {
		__defaultAssetReference:
			"data:framer/asset-reference,u6fApwxZkuyHfLmShbrytbQcmw.jpg?originalFilename=photo-1596097198305-e4844a56ddb8%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw0MHx8c3VzdGFpbmFibGV8ZW58MHx8fHwxNzQyMzkxMDc4fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 03",
		type: ControlType2.ResponsiveImage,
	},
	AI8ustKAD: {
		defaultValue: "Adaptability",
		displayTextArea: false,
		title: "Title 04",
		type: ControlType2.String,
	},
	QNMC8psw8: {
		defaultValue:
			"The world is constantly evolving, and so is architecture. We embrace flexibility in design, allowing spaces to adapt to changing needs, technologies, and lifestyles. Whether it\u2019s reconfigurable layouts, modular structures, or innovative materials, we ensure that our projects remain relevant and future-proof.",
		displayTextArea: false,
		title: "Description 04",
		type: ControlType2.String,
	},
	ZkLO10pL9: {
		__defaultAssetReference:
			"data:framer/asset-reference,LDjYU5dGcokAn2WS2qMzhYLofY.jpg?originalFilename=photo-1493663284031-b7e3aefcae8e%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxNHx8aG9tZXxlbnwwfHx8fDE3NDIzOTExNjB8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 04",
		type: ControlType2.ResponsiveImage,
	},
});
addFonts2(
	FramerZQuubFkEq,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...CardApproachFonts,
		...SlideshowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/ABOUT3-e9yP.js
var MotionDivWithFX = withFX(motion3.div);
var SlideshowApproachFonts = getFonts2(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(
	SmartComponentScopedContainer2,
);
var cycleOrder2 = ["wVxB9ra3S", "K_0zNOwOd", "d49mia8zk"];
var serializationHash3 = "framer-FLoK2";
var variantClassNames3 = {
	d49mia8zk: "framer-v-5xanqd",
	K_0zNOwOd: "framer-v-1df4a1x",
	wVxB9ra3S: "framer-v-q1l6a0",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 18,
};
var transition2 = {
	damping: 55,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "wVxB9ra3S",
	Phone: "d49mia8zk",
	Tablet: "K_0zNOwOd",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "wVxB9ra3S",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder2,
		defaultVariant: "wVxB9ra3S",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.section
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-q1l6a0",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"wVxB9ra3S"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								d49mia8zk: {
									"data-framer-name": "Phone",
								},
								K_0zNOwOd: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-qutfx2"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"VQW4_IhsH"}
						>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1f5s38n"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"mNzwm8Vu7"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1bt629a"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"eBczRWzX_"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-11asbfe"}
											data-styles-preset={"NtXagAClV"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
											}}
										>
											{"Approach"}
										</motion3.p>
									</React3.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-19euutn"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"TC4KoMndY"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion3.h2
											className={"framer-styles-preset-rdnt0j"}
											data-styles-preset={"wIgsXR7Fc"}
										>
											{"Designing with Purpose, Innovation, and Sustainability"}
										</motion3.h2>
									</React3.Fragment>
								</RichText2>
							</MotionDivWithFX>
							<ComponentViewportProvider2
								height={400}
								width={`min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px)`}
								y={
									(componentViewport?.y || 0) +
									(100 +
										((componentViewport?.height || 200) - 200 - 594.4) / 2) +
									0 +
									194.4
								}
								{...addPropertyOverrides2(
									{
										d49mia8zk: {
											height: 600,
											width: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
											y:
												(componentViewport?.y || 0) +
												(60 +
													((componentViewport?.height || 200) - 120 - 778.4) /
														2) +
												0 +
												178.4,
										},
										K_0zNOwOd: {
											height: 380,
											width: `min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px)`,
											y:
												(componentViewport?.y || 0) +
												(80 +
													((componentViewport?.height || 200) - 160 - 566.4) /
														2) +
												0 +
												186.4,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainerWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-i7kkbg-container"}
									layoutDependency={layoutDependency}
									layoutId={"uDlFc_Dhz-container"}
									nodeId={"uDlFc_Dhz"}
									rendersWithMotion={true}
									scopeId={"SfZvXm5b5"}
								>
									{_jsx3(stdin_default2, {
										AI8ustKAD: "Adaptability",
										height: "100%",
										id: "uDlFc_Dhz",
										layoutId: "uDlFc_Dhz",
										MTvFaXRgp: "Innovative Design",
										QNMC8psw8:
											"The world is constantly evolving, and so is architecture. We embrace flexibility in design, allowing spaces to adapt to changing needs, technologies, and lifestyles. Whether it\u2019s reconfigurable layouts, modular structures, or innovative materials, we ensure that our projects remain relevant and future-proof.",
										style: {
											height: "100%",
											width: "100%",
										},
										SyvApxOld:
											"We believe architecture should push boundaries, blending creativity with cutting-edge technology to create spaces that are both aesthetically striking and highly functional. Our designs embrace bold concepts, meticulous craftsmanship, and future-ready solutions that redefine the way people experience their surroundings.",
										tdtl2OItr: "Client-Centric Approach",
										uMNAV6X96:
											"We integrate eco-conscious strategies into every stage of design and construction, prioritizing energy efficiency, sustainable materials, and minimal environmental impact. By focusing on longevity and responsible design choices, we create buildings that harmonize with their surroundings and stand the test of time.",
										width: "100%",
										XZbNx08D5:
											"Every project starts with understanding our clients\u2019 vision, needs, and aspirations. We collaborate closely throughout the design process, ensuring that every detail aligns with their goals. Our tailored approach guarantees that each space is a true reflection of its users, balancing personal style with architectural excellence.",
										YDyPo_uqq: "BCZa_o_jN",
										ZrswWKKgU: "Sustainable Practices",
										...addPropertyOverrides2(
											{
												d49mia8zk: {
													YDyPo_uqq: "VaSi0S1Lm",
												},
												K_0zNOwOd: {
													YDyPo_uqq: "jhlxEmfjh",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainerWithFX>
							</ComponentViewportProvider2>
						</motion3.div>
					</motion3.section>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FLoK2.framer-1opwo1r, .framer-FLoK2 .framer-1opwo1r { display: block; }",
	".framer-FLoK2.framer-q1l6a0 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-FLoK2 .framer-qutfx2 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-FLoK2 .framer-1f5s38n { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 750px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-FLoK2 .framer-1bt629a, .framer-FLoK2 .framer-19euutn { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-FLoK2 .framer-i7kkbg-container { flex: none; height: 400px; position: relative; width: 100%; }",
	".framer-FLoK2.framer-v-1df4a1x.framer-q1l6a0 { padding: 80px 30px 80px 30px; width: 810px; }",
	".framer-FLoK2.framer-v-1df4a1x .framer-qutfx2 { gap: 56px; }",
	".framer-FLoK2.framer-v-1df4a1x .framer-i7kkbg-container { height: 380px; }",
	".framer-FLoK2.framer-v-5xanqd.framer-q1l6a0 { padding: 60px 16px 60px 16px; width: 200px; }",
	".framer-FLoK2.framer-v-5xanqd .framer-qutfx2 { gap: 48px; }",
	".framer-FLoK2.framer-v-5xanqd .framer-i7kkbg-container { height: 600px; }",
	...css,
	...css2,
];
var FramerSfZvXm5b5 = withCSS3(Component3, css7, "framer-FLoK2");
var stdin_default3 = FramerSfZvXm5b5;
FramerSfZvXm5b5.displayName = "ABOUT3";
FramerSfZvXm5b5.defaultProps = {
	height: 787,
	width: 1200,
};
addPropertyControls3(FramerSfZvXm5b5, {
	variant: {
		options: ["wVxB9ra3S", "K_0zNOwOd", "d49mia8zk"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts3(
	FramerSfZvXm5b5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SlideshowApproachFonts,
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:about3
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "d49mia8zk",
	md: "K_0zNOwOd",
	xl: "wVxB9ra3S",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders About3FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var about3_default = ComponentWithRoot;
export { about3_default as default };
