// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-5HVXZSBJ.js";
import {
	enumToDisplayNameFunctions,
	stdin_default as stdin_default2,
	stdin_default2 as stdin_default3,
} from "./chunks/chunk-VYISUX2Z.js";
import "./chunks/chunk-4KZCCVSQ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EQ6EOYNA.js";
import "./chunks/chunk-FYMJT4D6.js";
import { className, css, fonts } from "./chunks/chunk-MBDBQ6CG.js";
import "./chunks/chunk-2RKPPYFD.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:blog1
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/BLOG1-MWEC.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	PathVariablesContext,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useDynamicRefs,
	useLoadMorePaginatedQuery,
	useLocaleCode,
	useLocaleInfo,
	useQueryData,
	useRouter,
	useVariantState,
	withCSS,
	withInfiniteScroll,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CardPostFonts = getFonts(stdin_default3);
var SpinnerFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithInfiniteScroll = withInfiniteScroll(
	SmartComponentScopedContainer,
);
var cycleOrder = ["pzIg4h6Ig", "GW7xGRDkb", "aDfFRGo0r"];
var serializationHash = "framer-MOtfF";
var variantClassNames = {
	aDfFRGo0r: "framer-v-1boiged",
	GW7xGRDkb: "framer-v-1v3h9p",
	pzIg4h6Ig: "framer-v-1o31ow2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 7,
};
var transition2 = {
	damping: 64,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0.4,
	tokenization: "line",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var animation1 = {
	filter: "blur(7px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition3 = {
	damping: 58,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var textEffect1 = {
	effect: animation1,
	repeat: false,
	startDelay: 0.3,
	tokenization: "word",
	transition: transition3,
	trigger: "onMount",
	type: "appear",
};
var sharedDateFormatter = (value, formatOptions, locale) => {
	if (typeof value !== "string") return "";
	const date = new Date(value);
	if (isNaN(date.getTime())) return "";
	const fallbackLocale = "en-US";
	try {
		return date.toLocaleString(locale || fallbackLocale, formatOptions);
	} catch {
		return date.toLocaleString(fallbackLocale, formatOptions);
	}
};
var dateOptions = {
	dateStyle: "medium",
	timeZone: "UTC",
};
var toDateString = (value, activeLocale) => {
	return sharedDateFormatter(value, dateOptions, activeLocale);
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var loaderVariants = (repeaterState, variants, currentVariant) => {
	if (repeaterState.currentPage >= repeaterState.totalPages)
		return variants.disabled ?? currentVariant;
	if (repeaterState.isLoading) return variants.loading ?? currentVariant;
	return currentVariant;
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const { paginatedQuery, paginationInfo, loadMore } =
		useLoadMorePaginatedQuery(query2, pageSize, "O58UErRBA");
	const data = useQueryData(paginatedQuery);
	return children(data, paginationInfo, loadMore);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "pzIg4h6Ig",
	Phone: "aDfFRGo0r",
	Tablet: "GW7xGRDkb",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "pzIg4h6Ig",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		DBFSH4nWUO58UErRBA,
		c056J5fDhO58UErRBA,
		HdtjiToY0O58UErRBA,
		kaTwFTXUeO58UErRBA,
		zsbXziXbRO58UErRBA,
		zB_4_J7KJO58UErRBA,
		idO58UErRBA,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "pzIg4h6Ig",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const activeLocaleCode = useLocaleCode();
	const router = useRouter();
	const dynamicRef = useDynamicRefs();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1o31ow2",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"pzIg4h6Ig"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								aDfFRGo0r: {
									"data-framer-name": "Phone",
								},
								GW7xGRDkb: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-19bl8qp"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"hrZws466r"}
						>
							<motion.div
								className={"framer-1f43wid"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"rFZEwa0ON"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1rzjw0"}
									effect={textEffect}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"WbgD3vu05"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-11asbfe"}
											data-styles-preset={"NtXagAClV"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
											}}
										>
											{"Blogs"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1so1k2d"}
									effect={textEffect1}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kt2HqgmG8"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-1n41l9y"}
											data-styles-preset={"YMmsPodJ4"}
										>
											{"Latest Articles"}
										</motion.h1>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-t7oh2r"}
								layoutDependency={layoutDependency}
								layoutId={"O58UErRBA"}
							>
								<ChildrenCanSuspend>
									<QueryData
										pageSize={4}
										query={{
											from: {
												alias: "O58UErRBA",
												data: stdin_default2,
												type: "Collection",
											},
											select: [
												{
													collection: "O58UErRBA",
													name: "DBFSH4nWU",
													type: "Identifier",
												},
												{
													collection: "O58UErRBA",
													name: "c056J5fDh",
													type: "Identifier",
												},
												{
													collection: "O58UErRBA",
													name: "HdtjiToY0",
													type: "Identifier",
												},
												{
													collection: "O58UErRBA",
													name: "kaTwFTXUe",
													type: "Identifier",
												},
												{
													collection: "O58UErRBA",
													name: "zsbXziXbR",
													type: "Identifier",
												},
												{
													collection: "O58UErRBA",
													name: "zB_4_J7KJ",
													type: "Identifier",
												},
												{
													collection: "O58UErRBA",
													name: "id",
													type: "Identifier",
												},
											],
										}}
									>
										{(collection, paginationInfo, loadMore) => (
											<_Fragment>
												{collection?.map(
													(
														{
															c056J5fDh: c056J5fDhO58UErRBA2,
															DBFSH4nWU: DBFSH4nWUO58UErRBA2,
															HdtjiToY0: HdtjiToY0O58UErRBA2,
															id: idO58UErRBA2,
															kaTwFTXUe: kaTwFTXUeO58UErRBA2,
															zB_4_J7KJ: zB_4_J7KJO58UErRBA2,
															zsbXziXbR: zsbXziXbRO58UErRBA2,
														},
														index,
													) => {
														DBFSH4nWUO58UErRBA2 ??= "";
														c056J5fDhO58UErRBA2 ??= "";
														zB_4_J7KJO58UErRBA2 ??= "";
														return (
															<LayoutGroup key={idO58UErRBA2} id={`O58UErRBA-${idO58UErRBA2}`}>
																<PathVariablesContext.Provider
																	value={{
																		zB_4_J7KJ: zB_4_J7KJO58UErRBA2,
																	}}
																>
																	<ResolveLinks
																		links={[
																			{
																				href: {
																					pathVariables: {
																						zB_4_J7KJ: zB_4_J7KJO58UErRBA2,
																					},
																					webPageId: "J7MQjfzmq",
																				},
																				implicitPathVariables: void 0,
																			},
																			{
																				href: {
																					pathVariables: {
																						zB_4_J7KJ: zB_4_J7KJO58UErRBA2,
																					},
																					webPageId: "J7MQjfzmq",
																				},
																				implicitPathVariables: void 0,
																			},
																			{
																				href: {
																					pathVariables: {
																						zB_4_J7KJ: zB_4_J7KJO58UErRBA2,
																					},
																					webPageId: "J7MQjfzmq",
																				},
																				implicitPathVariables: void 0,
																			},
																		]}
																	>
																		{(resolvedLinks) => (
																			<ComponentViewportProvider
																				height={557}
																				width={`max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 60px) / 3, 50px)`}
																				y={
																					(componentViewport?.y || 0) +
																					(50 +
																						((componentViewport?.height ||
																							200) -
																							150 -
																							1355.2) /
																							2) +
																					0 +
																					211.2 +
																					0 +
																					0
																				}
																				{...addPropertyOverrides(
																					{
																						aDfFRGo0r: {
																							width: `max(min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px), 50px)`,
																							y:
																								(componentViewport?.y || 0) +
																								(30 +
																									((componentViewport?.height ||
																										200) -
																										90 -
																										1339.2) /
																										2) +
																								0 +
																								195.2 +
																								0 +
																								0,
																						},
																						GW7xGRDkb: {
																							width: `max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) - 30px) / 2, 50px)`,
																							y:
																								(componentViewport?.y || 0) +
																								(40 +
																									((componentViewport?.height ||
																										200) -
																										120 -
																										1347.2) /
																										2) +
																								0 +
																								203.2 +
																								0 +
																								0,
																						},
																					},
																					baseVariant,
																					gestureVariant,
																				)}
																			>
																				<SmartComponentScopedContainer
																					className={"framer-ep9qg8-container"}
																					layoutDependency={layoutDependency}
																					layoutId={"MITw0h30H-container"}
																					nodeId={"MITw0h30H"}
																					rendersWithMotion={true}
																					scopeId={"btLj1W3nU"}
																				>
																					{_jsx(stdin_default3, {
																						coAKtLBE6: c056J5fDhO58UErRBA2,
																						height: "100%",
																						id: "MITw0h30H",
																						KMIU38EBI: resolvedLinks[0],
																						layoutId: "MITw0h30H",
																						style: {
																							width: "100%",
																						},
																						tb1vdFx9x:
																							toResponsiveImage(
																								zsbXziXbRO58UErRBA2,
																							),
																						vvfxMxnaU: toDateString(
																							HdtjiToY0O58UErRBA2,
																							activeLocaleCode,
																						),
																						width: "100%",
																						wyOZ4oSby: DBFSH4nWUO58UErRBA2,
																						X102r6MZY:
																							enumToDisplayNameFunctions[
																								"kaTwFTXUe"
																							]?.(
																								kaTwFTXUeO58UErRBA2,
																								activeLocale,
																							),
																						...addPropertyOverrides(
																							{
																								aDfFRGo0r: {
																									KMIU38EBI: resolvedLinks[2],
																								},
																								GW7xGRDkb: {
																									KMIU38EBI: resolvedLinks[1],
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						),
																					})}
																				</SmartComponentScopedContainer>
																			</ComponentViewportProvider>
																		)}
																	</ResolveLinks>
																</PathVariablesContext.Provider>
															</LayoutGroup>
														);
													},
												)}
												<ComponentViewportProvider
													height={40}
													y={
														(componentViewport?.y || 0) +
														(50 +
															((componentViewport?.height || 200) -
																150 -
																1355.2) /
																2) +
														0 +
														211.2 +
														1144 -
														40
													}
													{...addPropertyOverrides(
														{
															aDfFRGo0r: {
																y:
																	(componentViewport?.y || 0) +
																	(30 +
																		((componentViewport?.height || 200) -
																			90 -
																			1339.2) /
																			2) +
																	0 +
																	195.2 +
																	1144 -
																	40,
															},
															GW7xGRDkb: {
																y:
																	(componentViewport?.y || 0) +
																	(40 +
																		((componentViewport?.height || 200) -
																			120 -
																			1347.2) /
																			2) +
																	0 +
																	203.2 +
																	1144 -
																	40,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithInfiniteScroll
														__loadMore={loadMore}
														__paginationInfo={paginationInfo}
														className={"framer-1m4dusd-container"}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"NAAn2dri3-container"}
														nodeId={"NAAn2dri3"}
														ref={dynamicRef(
															`${zB_4_J7KJO58UErRBA}-${layoutId}-1m4dusd`,
														)}
														rendersWithMotion={true}
														scopeId={"btLj1W3nU"}
														transformTemplate={transformTemplate1}
													>
														{_jsx(stdin_default, {
															height: "100%",
															id: "NAAn2dri3",
															layoutId: "NAAn2dri3",
															variant: loaderVariants(
																paginationInfo,
																{
																	disabled: "PX1MOnVXY",
																	loading: "G47S15YSn",
																},
																"G47S15YSn",
															),
															width: "100%",
														})}
													</SmartComponentScopedContainerWithInfiniteScroll>
												</ComponentViewportProvider>
											</_Fragment>
										)}
									</QueryData>
								</ChildrenCanSuspend>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MOtfF.framer-1dk17q0, .framer-MOtfF .framer-1dk17q0 { display: block; }",
	".framer-MOtfF.framer-1o31ow2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 50px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-MOtfF .framer-19bl8qp { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-MOtfF .framer-1f43wid { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 750px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-MOtfF .framer-1rzjw0, .framer-MOtfF .framer-1so1k2d { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-MOtfF .framer-t7oh2r { display: grid; flex: none; gap: 30px 30px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(3, minmax(50px, 1fr)); height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-MOtfF .framer-ep9qg8-container { align-self: start; flex: none; height: auto; justify-self: start; position: relative; width: 100%; }",
	".framer-MOtfF .framer-1m4dusd-container { bottom: 0px; flex: none; height: auto; left: 50%; position: absolute; width: auto; }",
	".framer-MOtfF.framer-v-1v3h9p.framer-1o31ow2 { padding: 40px 30px 80px 30px; width: 810px; }",
	".framer-MOtfF.framer-v-1v3h9p .framer-19bl8qp { gap: 56px; }",
	".framer-MOtfF.framer-v-1v3h9p .framer-t7oh2r { grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-MOtfF.framer-v-1boiged.framer-1o31ow2 { padding: 30px 16px 60px 16px; width: 200px; }",
	".framer-MOtfF.framer-v-1boiged .framer-19bl8qp { gap: 48px; }",
	".framer-MOtfF.framer-v-1boiged .framer-t7oh2r { grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	...css,
	...css2,
];
var FramerbtLj1W3nU = withCSS(Component, css3, "framer-MOtfF");
var stdin_default4 = FramerbtLj1W3nU;
FramerbtLj1W3nU.displayName = "BLOG1";
FramerbtLj1W3nU.defaultProps = {
	height: 1484,
	width: 1200,
};
addPropertyControls(FramerbtLj1W3nU, {
	variant: {
		options: ["pzIg4h6Ig", "GW7xGRDkb", "aDfFRGo0r"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerbtLj1W3nU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CardPostFonts,
		...SpinnerFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blog1
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aDfFRGo0r",
	md: "GW7xGRDkb",
	xl: "pzIg4h6Ig",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Blog1FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var blog1_default = ComponentWithRoot;
export { blog1_default as default };
