// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-MKQAZJB5.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-6CKA3WKL.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-EQ6EOYNA.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-N4SVWGDY.js";
import "./chunks/chunk-IICRMQVR.js";
import { className, css, fonts } from "./chunks/chunk-MBDBQ6CG.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:contact2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/CONTACT2-3w3z.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var FormFonts = getFonts(stdin_default);
var cycleOrder = ["lbW1y4AUz", "MTYNM1NSG", "HVtz9SR57"];
var serializationHash = "framer-odWgG";
var variantClassNames = {
	HVtz9SR57: "framer-v-14jdl45",
	lbW1y4AUz: "framer-v-1gzpoj1",
	MTYNM1NSG: "framer-v-xr8h1e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	filter: "blur(7px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	damping: 58,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0.3,
	tokenization: "word",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
	}
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "lbW1y4AUz",
	Phone: "HVtz9SR57",
	Tablet: "MTYNM1NSG",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lbW1y4AUz",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lbW1y4AUz",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2, className4];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1gzpoj1",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"lbW1y4AUz"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								HVtz9SR57: {
									"data-framer-name": "Phone",
								},
								MTYNM1NSG: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-pxutwj"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"T4JTIfokl"}
						>
							<motion.div
								className={"framer-qrm26i"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"iJ1eMD5hw"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1st0ktv"}
									effect={textEffect}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"rCPxROt_M"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-11asbfe"}
											data-styles-preset={"NtXagAClV"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
											}}
										>
											{"Get In Touch"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-19xraik"}
									effect={textEffect}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"BwmQj8TLT"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-1n41l9y"}
											data-styles-preset={"YMmsPodJ4"}
										>
											{"Contact us"}
										</motion.h1>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-i9f3em"}
								data-framer-name={"Contact"}
								layoutDependency={layoutDependency}
								layoutId={"eEo3uHSJ_"}
							>
								<motion.div
									className={"framer-vb0uir"}
									data-framer-name={"Form"}
									layoutDependency={layoutDependency}
									layoutId={"ocbRyapD9"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-18167yh"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"UqGnMjUPW"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-144gy8o"}
												data-styles-preset={"qA7GDH1GX"}
											>
												{
													"We\u2019d love to hear from you! Whether you have a new project in mind, need expert consultation, or just want to learn more about our work, our team is ready to assist. Reach out to us, and let\u2019s create something remarkable."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
									<FormContainer
										className={"framer-9gr0a6"}
										layoutDependency={layoutDependency}
										layoutId={"LcP_odh7s"}
										nodeId={"LcP_odh7s"}
									>
										{(formState) => (
											<_Fragment>
												<motion.label
													className={"framer-1lew7vi"}
													layoutDependency={layoutDependency}
													layoutId={"AOcLAikhD"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-t92c1p"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"mTKgsGBb8"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1c1u61y"}
																data-styles-preset={"ZAj2AL4BA"}
															>
																{"First Name"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<FormPlainTextInput
														className={"framer-xz920x"}
														inputName={"First Name"}
														layoutDependency={layoutDependency}
														layoutId={"Ava1SxwZ7"}
														placeholder={"Jane"}
														style={{
															"--framer-input-background":
																"var(--token-bcae30db-da05-4a45-9392-f0131d182fb4, rgba(18, 18, 18, 0.03))",
															"--framer-input-border-bottom-width": "1px",
															"--framer-input-border-color":
																"var(--token-93add2ba-17c9-4f58-976f-415dbcf07227, rgba(18, 18, 18, 0.05))",
															"--framer-input-border-left-width": "1px",
															"--framer-input-border-right-width": "1px",
															"--framer-input-border-style": "solid",
															"--framer-input-border-top-width": "1px",
															"--framer-input-font-color":
																"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
															"--framer-input-icon-color": "rgb(153, 153, 153)",
															"--framer-input-placeholder-color":
																"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
														}}
														type={"text"}
													/>
												</motion.label>
												<motion.label
													className={"framer-hqtg98"}
													layoutDependency={layoutDependency}
													layoutId={"PoxNa1xeB"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-169c10v"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"jKtt_rRW5"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1c1u61y"}
																data-styles-preset={"ZAj2AL4BA"}
															>
																{"Last Name"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<FormPlainTextInput
														className={"framer-rg9iyx"}
														inputName={"Last Name"}
														layoutDependency={layoutDependency}
														layoutId={"s32ohEWx9"}
														placeholder={"Smith"}
														style={{
															"--framer-input-background":
																"var(--token-bcae30db-da05-4a45-9392-f0131d182fb4, rgba(18, 18, 18, 0.03))",
															"--framer-input-border-bottom-width": "1px",
															"--framer-input-border-color":
																"var(--token-93add2ba-17c9-4f58-976f-415dbcf07227, rgba(18, 18, 18, 0.05))",
															"--framer-input-border-left-width": "1px",
															"--framer-input-border-right-width": "1px",
															"--framer-input-border-style": "solid",
															"--framer-input-border-top-width": "1px",
															"--framer-input-font-color":
																"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
															"--framer-input-icon-color": "rgb(153, 153, 153)",
															"--framer-input-placeholder-color":
																"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
														}}
														type={"text"}
													/>
												</motion.label>
												<motion.label
													className={"framer-1pdi7rc"}
													layoutDependency={layoutDependency}
													layoutId={"wUtsdsrPz"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-heguw2"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"qlocXu3y3"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1c1u61y"}
																data-styles-preset={"ZAj2AL4BA"}
															>
																{"Email"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<FormPlainTextInput
														className={"framer-1eieefx"}
														inputName={"Email"}
														layoutDependency={layoutDependency}
														layoutId={"aB58N7LWV"}
														placeholder={"jane@framer.com"}
														style={{
															"--framer-input-background":
																"var(--token-bcae30db-da05-4a45-9392-f0131d182fb4, rgba(18, 18, 18, 0.03))",
															"--framer-input-border-bottom-width": "1px",
															"--framer-input-border-color":
																"var(--token-93add2ba-17c9-4f58-976f-415dbcf07227, rgba(18, 18, 18, 0.05))",
															"--framer-input-border-left-width": "1px",
															"--framer-input-border-right-width": "1px",
															"--framer-input-border-style": "solid",
															"--framer-input-border-top-width": "1px",
															"--framer-input-font-color":
																"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
															"--framer-input-icon-color": "rgb(153, 153, 153)",
															"--framer-input-placeholder-color":
																"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
														}}
														type={"email"}
													/>
												</motion.label>
												<motion.label
													className={"framer-b4g2xn"}
													layoutDependency={layoutDependency}
													layoutId={"wS6EdlNsj"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-w02gcy"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"NztMVu9tR"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1c1u61y"}
																data-styles-preset={"ZAj2AL4BA"}
															>
																{"Phone"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<FormPlainTextInput
														className={"framer-723x6w"}
														inputName={"Phone"}
														layoutDependency={layoutDependency}
														layoutId={"y4WlKsXOx"}
														placeholder={"+1 (212) 555-7890"}
														style={{
															"--framer-input-background":
																"var(--token-bcae30db-da05-4a45-9392-f0131d182fb4, rgba(18, 18, 18, 0.03))",
															"--framer-input-border-bottom-width": "1px",
															"--framer-input-border-color":
																"var(--token-93add2ba-17c9-4f58-976f-415dbcf07227, rgba(18, 18, 18, 0.05))",
															"--framer-input-border-left-width": "1px",
															"--framer-input-border-right-width": "1px",
															"--framer-input-border-style": "solid",
															"--framer-input-border-top-width": "1px",
															"--framer-input-font-color":
																"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
															"--framer-input-icon-color": "rgb(153, 153, 153)",
															"--framer-input-placeholder-color":
																"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
														}}
														type={"tel"}
													/>
												</motion.label>
												<motion.label
													className={"framer-1m7tamj"}
													layoutDependency={layoutDependency}
													layoutId={"VNf5ptBvJ"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-lpom7o"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"C8tjmxL_T"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1c1u61y"}
																data-styles-preset={"ZAj2AL4BA"}
															>
																{"Message"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<FormPlainTextInput
														className={"framer-1ccjbem"}
														inputName={"Message"}
														layoutDependency={layoutDependency}
														layoutId={"XnladJnlz"}
														placeholder={"Type something ..."}
														style={{
															"--framer-input-background":
																"var(--token-bcae30db-da05-4a45-9392-f0131d182fb4, rgba(18, 18, 18, 0.03))",
															"--framer-input-border-bottom-width": "1px",
															"--framer-input-border-color":
																"var(--token-93add2ba-17c9-4f58-976f-415dbcf07227, rgba(18, 18, 18, 0.05))",
															"--framer-input-border-left-width": "1px",
															"--framer-input-border-right-width": "1px",
															"--framer-input-border-style": "solid",
															"--framer-input-border-top-width": "1px",
															"--framer-input-font-color":
																"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
															"--framer-input-icon-color": "rgb(153, 153, 153)",
															"--framer-input-placeholder-color":
																"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
														}}
														type={"textarea"}
													/>
												</motion.label>
												<ComponentViewportProvider height={40}>
													<SmartComponentScopedContainer
														className={"framer-1rknt3b-container"}
														layoutDependency={layoutDependency}
														layoutId={"BBBod9PN7-container"}
														nodeId={"BBBod9PN7"}
														rendersWithMotion={true}
														scopeId={"iKaQNjJ7T"}
													>
														{_jsx(stdin_default, {
															height: "100%",
															id: "BBBod9PN7",
															layoutId: "BBBod9PN7",
															LrVMtctGw: "Submit",
															lxm6tyTiZ:
																"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
															style: {
																height: "100%",
															},
															type: "submit",
															variant: formVariants(
																formState,
																{
																	error: "P4L2ryOXz",
																	pending: "uq6zPUICF",
																	success: "O45jLN0rS",
																},
																"mOoSvetA8",
															),
															width: "100%",
															ySlgjs70q:
																"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</_Fragment>
										)}
									</FormContainer>
								</motion.div>
								<Image
									background={{
										alt: "",
										fit: "fill",
										pixelHeight: 6e3,
										pixelWidth: 4e3,
										sizes: `max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 48px) / 2, 1px)`,
										src: "https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg",
										srcSet:
											"https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg 4000w",
									}}
									className={"framer-c6xbrt"}
									layoutDependency={layoutDependency}
									layoutId={"ZgALG1ptY"}
									{...addPropertyOverrides(
										{
											HVtz9SR57: {
												background: {
													alt: "",
													fit: "fill",
													pixelHeight: 6e3,
													pixelWidth: 4e3,
													sizes: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
													src: "https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg",
													srcSet:
														"https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg 4000w",
												},
											},
											MTYNM1NSG: {
												background: {
													alt: "",
													fit: "fill",
													pixelHeight: 6e3,
													pixelWidth: 4e3,
													sizes: `min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px)`,
													src: "https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg",
													srcSet:
														"https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/SZYzatynoitkP4V2MREEXwzsMA.jpg 4000w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-odWgG.framer-1aj9z14, .framer-odWgG .framer-1aj9z14 { display: block; }",
	".framer-odWgG.framer-1gzpoj1 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 50px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-odWgG .framer-pxutwj { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-odWgG .framer-qrm26i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 750px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-odWgG .framer-1st0ktv, .framer-odWgG .framer-19xraik, .framer-odWgG .framer-18167yh { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-odWgG .framer-i9f3em { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-odWgG .framer-vb0uir { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-odWgG .framer-9gr0a6 { display: grid; flex: none; gap: 24px; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-odWgG .framer-1lew7vi, .framer-odWgG .framer-hqtg98, .framer-odWgG .framer-1pdi7rc, .framer-odWgG .framer-b4g2xn { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; justify-self: start; padding: 0px; position: relative; width: 100%; }",
	".framer-odWgG .framer-t92c1p, .framer-odWgG .framer-169c10v, .framer-odWgG .framer-heguw2, .framer-odWgG .framer-w02gcy, .framer-odWgG .framer-lpom7o { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-odWgG .framer-xz920x, .framer-odWgG .framer-rg9iyx, .framer-odWgG .framer-1eieefx, .framer-odWgG .framer-723x6w { --framer-input-focused-border-color: var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3)); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Plus Jakarta Sans"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 12px; flex: none; height: 44px; position: relative; width: 100%; }',
	".framer-odWgG .framer-1m7tamj { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; grid-column: span 2; height: min-content; justify-content: flex-start; justify-self: start; padding: 0px; position: relative; width: 100%; }",
	'.framer-odWgG .framer-1ccjbem { --framer-input-focused-border-color: var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3)); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Plus Jakarta Sans"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 12px; --framer-input-wrapper-height: auto; --framer-textarea-resize: vertical; flex: none; height: auto; min-height: 200px; position: relative; width: 100%; }',
	".framer-odWgG .framer-1rknt3b-container { align-self: start; flex: none; height: 40px; justify-self: start; position: relative; width: fit-content; }",
	".framer-odWgG .framer-c6xbrt { align-self: stretch; flex: 1 0 0px; height: auto; overflow: hidden; position: relative; width: 1px; }",
	".framer-odWgG.framer-v-xr8h1e.framer-1gzpoj1 { padding: 40px 30px 80px 30px; width: 810px; }",
	".framer-odWgG.framer-v-xr8h1e .framer-pxutwj { gap: 56px; }",
	".framer-odWgG.framer-v-xr8h1e .framer-i9f3em, .framer-odWgG.framer-v-14jdl45 .framer-i9f3em { flex-direction: column; }",
	".framer-odWgG.framer-v-xr8h1e .framer-vb0uir, .framer-odWgG.framer-v-14jdl45 .framer-vb0uir { flex: none; width: 100%; }",
	".framer-odWgG.framer-v-xr8h1e .framer-c6xbrt { align-self: unset; aspect-ratio: 2.5 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 80px); width: 100%; }",
	".framer-odWgG.framer-v-14jdl45.framer-1gzpoj1 { padding: 30px 16px 60px 16px; width: 390px; }",
	".framer-odWgG.framer-v-14jdl45 .framer-pxutwj { gap: 48px; }",
	".framer-odWgG.framer-v-14jdl45 .framer-9gr0a6 { grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	".framer-odWgG.framer-v-14jdl45 .framer-1m7tamj { grid-column: span 1; }",
	".framer-odWgG.framer-v-14jdl45 .framer-c6xbrt { align-self: unset; flex: none; height: 200px; width: 100%; }",
	...css,
	...css3,
	...css2,
	...css4,
];
var FrameriKaQNjJ7T = withCSS(Component, css5, "framer-odWgG");
var stdin_default2 = FrameriKaQNjJ7T;
FrameriKaQNjJ7T.displayName = "CONTACT2";
FrameriKaQNjJ7T.defaultProps = {
	height: 930,
	width: 1200,
};
addPropertyControls(FrameriKaQNjJ7T, {
	variant: {
		options: ["lbW1y4AUz", "MTYNM1NSG", "HVtz9SR57"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameriKaQNjJ7T,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Plus Jakarta Sans",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TX2N2Q6ZO2LBO34H72H5RVJTBQFGU4GV/ZICVNTLTT4V7CCIJPWNY363N6LIP2AET/OUUAK2X2MEGEKC6ULA4CFSBY4PE5EGPV.woff2",
					weight: "400",
				},
			],
		},
		...FormFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:contact2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HVtz9SR57",
	md: "MTYNM1NSG",
	xl: "lbW1y4AUz",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Contact2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var contact2_default = ComponentWithRoot;
export { contact2_default as default };
