// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-IICRMQVR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-2RKPPYFD.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:cta
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/CTA-InA6.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts2,
	ResolveLinks,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useRouter,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/42CYxvMnf1AraNM9uI07/GDtQN3zyw3DjKUNM1nSb/H71V2HcH2.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	Image,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/sFrVUWLdB132zMzz4ndq/dcvmJf3VeiKqkFrgICtC/wIgsXR7Fc.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Plus Jakarta Sans-medium",
	"FS;Plus Jakarta Sans-bold",
	"FS;Plus Jakarta Sans-bold italic",
	"FS;Plus Jakarta Sans-medium italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/3U7D2WJULAFN5UCDE2DSKFPDTJNUSRPY/XTZGHUDFURQVBRVTOPX7XHP5YBIQJL2U/FVNNCZHGTHUOM3RCJDOO45QMBIJISVEG.woff2",
				weight: "500",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/AJVGEOXGB2ALQKAZEK2LDOLCVBCMCOIT/LDEP4R7SNNABDEG433DCQGM2A7YCBHLU/OWABOLGBAKFVLPZ756IYS6EKYKU54K3I.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/57U2OK2BISA74Z4RT4CRD5GR4O3PNVPY/K4TDAPUNBYK24HOCNW4JIOTEXSAE2BEF/GV5XODI2YD2DJA5RVTMJOSDHYESL7IYT.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/UABF25CCX23LBLOOMOCUSPFEXYUNKOIQ/NGF5IU7BZUA2FUOVWECHGUFSHNEIX4YK/QDINYT7WQXBD2IDFQGGJ74DWIUFHOOZD.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	'.framer-Ay7Ks .framer-styles-preset-rdnt0j:not(.rich-text-wrapper), .framer-Ay7Ks .framer-styles-preset-rdnt0j.rich-text-wrapper h2 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 42px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, #121212); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-Ay7Ks .framer-styles-preset-rdnt0j:not(.rich-text-wrapper), .framer-Ay7Ks .framer-styles-preset-rdnt0j.rich-text-wrapper h2 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, #121212); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-Ay7Ks .framer-styles-preset-rdnt0j:not(.rich-text-wrapper), .framer-Ay7Ks .framer-styles-preset-rdnt0j.rich-text-wrapper h2 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, #121212); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-Ay7Ks";

// /:https://framerusercontent.com/modules/Gr13CgSh7vz355X0N668/bfd79kCTXPeDPaoi1rEl/PNpcbf775.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	aksiOF21h: {
		hover: true,
	},
	c1NRWquIu: {
		hover: true,
	},
	GQY9EfGY4: {
		hover: true,
	},
	n8lvtynAo: {
		hover: true,
	},
};
var cycleOrder = ["GQY9EfGY4", "c1NRWquIu", "n8lvtynAo", "aksiOF21h"];
var serializationHash = "framer-rBT3B";
var variantClassNames = {
	aksiOF21h: "framer-v-v7mogj",
	c1NRWquIu: "framer-v-ndtc97",
	GQY9EfGY4: "framer-v-uy3e5r",
	n8lvtynAo: "framer-v-qjs5y7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.5,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Accent - Black": "n8lvtynAo",
	"Accent - White": "aksiOF21h",
	Black: "GQY9EfGY4",
	White: "c1NRWquIu",
};
var getProps = ({ height, id, link, text, width, ...props }) => {
	return {
		...props,
		A1mdPRDCS: text ?? props.A1mdPRDCS ?? "Button",
		KKQ6Z0zNX: link ?? props.KKQ6Z0zNX,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "GQY9EfGY4",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		A1mdPRDCS,
		KKQ6Z0zNX,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "GQY9EfGY4",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={KKQ6Z0zNX}
						motionChild={true}
						nodeId={"GQY9EfGY4"}
						scopeId={"PNpcbf775"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-uy3e5r", className4, classNames)} framer-1q60qzc`}
							data-framer-name={"Black"}
							layoutDependency={layoutDependency}
							layoutId={"GQY9EfGY4"}
							ref={refBinding}
							style={{
								backgroundColor:
									"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
								...style,
							}}
							variants={{
								"aksiOF21h-hover": {
									backgroundColor:
										"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
								},
								"c1NRWquIu-hover": {
									backgroundColor:
										"var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54))",
								},
								"GQY9EfGY4-hover": {
									backgroundColor:
										"var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54))",
								},
								"n8lvtynAo-hover": {
									backgroundColor:
										"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
								},
								aksiOF21h: {
									backgroundColor:
										"var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54))",
								},
								c1NRWquIu: {
									backgroundColor:
										"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
								},
								n8lvtynAo: {
									backgroundColor:
										"var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54))",
								},
							}}
							{...addPropertyOverrides(
								{
									"aksiOF21h-hover": {
										"data-framer-name": void 0,
									},
									"c1NRWquIu-hover": {
										"data-framer-name": void 0,
									},
									"GQY9EfGY4-hover": {
										"data-framer-name": void 0,
									},
									"n8lvtynAo-hover": {
										"data-framer-name": void 0,
									},
									aksiOF21h: {
										"data-framer-name": "Accent - White",
									},
									c1NRWquIu: {
										"data-framer-name": "White",
									},
									n8lvtynAo: {
										"data-framer-name": "Accent - Black",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1f40yq0"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"olNk2ggxz"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={A1mdPRDCS}
								variants={{
									"aksiOF21h-hover": {
										"--extracted-r6o4lv":
											"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
									},
									"c1NRWquIu-hover": {
										"--extracted-r6o4lv":
											"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
									},
									c1NRWquIu: {
										"--extracted-r6o4lv":
											"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"aksiOF21h-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-19fqac6"}
														data-styles-preset={"gM0kQmWMx"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
										"c1NRWquIu-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-19fqac6"}
														data-styles-preset={"gM0kQmWMx"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
										c1NRWquIu: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-19fqac6"}
														data-styles-preset={"gM0kQmWMx"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-19fqac6"}
										data-styles-preset={"gM0kQmWMx"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255)))",
										}}
									>
										{"Button"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rBT3B.framer-1q60qzc, .framer-rBT3B .framer-1q60qzc { display: block; }",
	".framer-rBT3B.framer-uy3e5r { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 20px 10px 20px; position: relative; text-decoration: none; width: min-content; }",
	".framer-rBT3B .framer-1f40yq0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-rBT3B.framer-uy3e5r { gap: 0px; } .framer-rBT3B.framer-uy3e5r > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-rBT3B.framer-uy3e5r > :first-child { margin-left: 0px; } .framer-rBT3B.framer-uy3e5r > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerPNpcbf775 = withCSS(Component, css4, "framer-rBT3B");
var stdin_default = FramerPNpcbf775;
FramerPNpcbf775.displayName = "Button/Primary";
FramerPNpcbf775.defaultProps = {
	height: 33,
	width: 86,
};
addPropertyControls(FramerPNpcbf775, {
	variant: {
		options: ["GQY9EfGY4", "c1NRWquIu", "n8lvtynAo", "aksiOF21h"],
		optionTitles: ["Black", "White", "Accent - Black", "Accent - White"],
		title: "Variant",
		type: ControlType.Enum,
	},
	A1mdPRDCS: {
		defaultValue: "Button",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	KKQ6Z0zNX: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerPNpcbf775,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/42CYxvMnf1AraNM9uI07/GDtQN3zyw3DjKUNM1nSb/H71V2HcH2.js
var ButtonPrimaryFonts = getFonts(stdin_default);
var cycleOrder2 = ["kXtYalJ6I", "YCrTzZbk9", "pn2aGgou5"];
var serializationHash2 = "framer-oAmhi";
var variantClassNames2 = {
	kXtYalJ6I: "framer-v-h0ba2e",
	pn2aGgou5: "framer-v-1eo4l0e",
	YCrTzZbk9: "framer-v-c0golq",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "kXtYalJ6I",
	Phone: "pn2aGgou5",
	Tablet: "YCrTzZbk9",
};
var getProps2 = ({
	buttonLink,
	buttonText,
	description,
	height,
	id,
	title,
	width,
	...props
}) => {
	return {
		...props,
		gTy084auZ: buttonLink ?? props.gTy084auZ,
		TV5ImfK4l:
			title ?? props.TV5ImfK4l ?? "Transforming spaces,\u2028inspiring lives.",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "kXtYalJ6I",
		xlG7kue9w: buttonText ?? props.xlG7kue9w ?? "Contact us",
		xq26f_BEN:
			description ??
			props.xq26f_BEN ??
			"Ready to create something extraordinary? Whether you're designing a dream home, a cutting-edge workplace, or a sustainable urban space, we\u2019re here to turn your ideas into reality.",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		TV5ImfK4l,
		xq26f_BEN,
		xlG7kue9w,
		gTy084auZ,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "kXtYalJ6I",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Image
						{...restProps}
						{...gestureHandlers}
						as={"section"}
						background={{
							alt: "",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 1770,
							pixelWidth: 3600,
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/nt1eTHwsDpfxDePq7x9vLe9MWo.png",
							srcSet:
								"https://framerusercontent.com/images/nt1eTHwsDpfxDePq7x9vLe9MWo.png?scale-down-to=512 512w,https://framerusercontent.com/images/nt1eTHwsDpfxDePq7x9vLe9MWo.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/nt1eTHwsDpfxDePq7x9vLe9MWo.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/nt1eTHwsDpfxDePq7x9vLe9MWo.png 3600w",
						}}
						className={cx2(
							scopingClassNames,
							"framer-h0ba2e",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"kXtYalJ6I"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								pn2aGgou5: {
									"data-framer-name": "Phone",
								},
								YCrTzZbk9: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-yblesz"}
							data-framer-name={"Cover"}
							layoutDependency={layoutDependency}
							layoutId={"IB9tMulB8"}
							style={{
								background:
									"linear-gradient(180deg, rgba(18, 18, 18, 0) 0%, var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18)) 100%)",
							}}
						>
							<motion2.div
								className={"framer-1tp730m"}
								data-framer-name={"Inner"}
								layoutDependency={layoutDependency}
								layoutId={"Jaf_Y29l7"}
							>
								<motion2.div
									className={"framer-fqtjfo"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"iuxZnhcp9"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-1jdojg"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"E_tx80ahT"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={TV5ImfK4l}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.h2
												className={"framer-styles-preset-rdnt0j"}
												data-styles-preset={"wIgsXR7Fc"}
												style={{
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255)))",
												}}
											>
												{"Transforming spaces,\u2028\u2028inspiring lives."}
											</motion2.h2>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-ox6crs"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"y3RKBAa6Q"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={xq26f_BEN}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-144gy8o"}
												data-styles-preset={"qA7GDH1GX"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-2d9fdd1c-9481-4d00-acc8-5058d9aa515e, rgb(255, 255, 255)))",
												}}
											>
												{
													"Ready to create something extraordinary? Whether you're designing a dream home, a cutting-edge workplace, or a sustainable urban space, we\u2019re here to turn your ideas into reality."
												}
											</motion2.p>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
								<ComponentViewportProvider
									height={33}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 667) - 0 - 661.4) / 2) +
										300 +
										0 +
										228.4
									}
									{...addPropertyOverrides2(
										{
											pn2aGgou5: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 550) - 0 - 471.4) /
															2) +
													150 +
													0 +
													228.4,
											},
											YCrTzZbk9: {
												y:
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 597) - 0 - 591.4) /
															2) +
													250 +
													0 +
													228.4,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-lqr5b4-container"}
										layoutDependency={layoutDependency}
										layoutId={"jbV8LE5ws-container"}
										nodeId={"jbV8LE5ws"}
										rendersWithMotion={true}
										scopeId={"H71V2HcH2"}
									>
										{_jsx2(stdin_default, {
											A1mdPRDCS: xlG7kue9w,
											height: "100%",
											id: "jbV8LE5ws",
											KKQ6Z0zNX: gTy084auZ,
											layoutId: "jbV8LE5ws",
											variant: "aksiOF21h",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
					</Image>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oAmhi.framer-m7h770, .framer-oAmhi .framer-m7h770 { display: block; }",
	".framer-oAmhi.framer-h0ba2e { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-oAmhi .framer-yblesz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 300px 50px 100px 50px; position: relative; width: 1px; }",
	".framer-oAmhi .framer-1tp730m { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 42px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-oAmhi .framer-fqtjfo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 600px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-oAmhi .framer-1jdojg { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-oAmhi .framer-ox6crs { flex: none; height: auto; max-width: 500px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-oAmhi .framer-lqr5b4-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-oAmhi.framer-v-c0golq.framer-h0ba2e { width: 810px; }",
	".framer-oAmhi.framer-v-c0golq .framer-yblesz { padding: 250px 30px 80px 30px; }",
	".framer-oAmhi.framer-v-1eo4l0e.framer-h0ba2e { width: 390px; }",
	".framer-oAmhi.framer-v-1eo4l0e .framer-yblesz { padding: 150px 16px 60px 16px; }",
	...css3,
	...css2,
];
var FramerH71V2HcH2 = withCSS2(Component2, css5, "framer-oAmhi");
var stdin_default2 = FramerH71V2HcH2;
FramerH71V2HcH2.displayName = "Section/CTA";
FramerH71V2HcH2.defaultProps = {
	height: 667,
	width: 1200,
};
addPropertyControls2(FramerH71V2HcH2, {
	variant: {
		options: ["kXtYalJ6I", "YCrTzZbk9", "pn2aGgou5"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	TV5ImfK4l: {
		defaultValue: "Transforming spaces,\u2028inspiring lives.",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	xq26f_BEN: {
		defaultValue:
			"Ready to create something extraordinary? Whether you're designing a dream home, a cutting-edge workplace, or a sustainable urban space, we\u2019re here to turn your ideas into reality.",
		displayTextArea: false,
		title: "Description",
		type: ControlType2.String,
	},
	xlG7kue9w: {
		defaultValue: "Contact us",
		displayTextArea: false,
		title: "Button Text",
		type: ControlType2.String,
	},
	gTy084auZ: {
		title: "Button Link",
		type: ControlType2.Link,
	},
});
addFonts2(
	FramerH71V2HcH2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonPrimaryFonts,
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/CTA-InA6.js
var SectionCTAFonts = getFonts2(stdin_default2);
var cycleOrder3 = ["RxBB4n2Nx", "tSE9Czm1u", "VScSZyOaR"];
var serializationHash3 = "framer-J5ZEz";
var variantClassNames3 = {
	RxBB4n2Nx: "framer-v-lq1iae",
	tSE9Czm1u: "framer-v-1eacoaa",
	VScSZyOaR: "framer-v-19yr4ub",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap3 = {
	Desktop: "RxBB4n2Nx",
	Phone: "VScSZyOaR",
	Tablet: "tSE9Czm1u",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "RxBB4n2Nx",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "RxBB4n2Nx",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-lq1iae",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"RxBB4n2Nx"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides3(
							{
								tSE9Czm1u: {
									"data-framer-name": "Tablet",
								},
								VScSZyOaR: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "WOrYUhfBH",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "WOrYUhfBH",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										webPageId: "WOrYUhfBH",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<ComponentViewportProvider2
									height={667}
									width={`max(${componentViewport?.width || "100vw"}, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(100 + ((componentViewport?.height || 867) - 200 - 667) / 2)
									}
									{...addPropertyOverrides3(
										{
											tSE9Czm1u: {
												y:
													(componentViewport?.y || 0) +
													(80 +
														((componentViewport?.height || 757) - 160 - 667) /
															2),
											},
											VScSZyOaR: {
												y:
													(componentViewport?.y || 0) +
													(60 +
														((componentViewport?.height || 670) - 120 - 667) /
															2),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1jrrzjx-container"}
										layoutDependency={layoutDependency}
										layoutId={"aIu8TTErE-container"}
										nodeId={"aIu8TTErE"}
										rendersWithMotion={true}
										scopeId={"MFLZMQtsg"}
									>
										{_jsx3(stdin_default2, {
											gTy084auZ: resolvedLinks[0],
											height: "100%",
											id: "aIu8TTErE",
											layoutId: "aIu8TTErE",
											style: {
												width: "100%",
											},
											TV5ImfK4l: "Transforming spaces,\u2028inspiring lives.",
											variant: "kXtYalJ6I",
											width: "100%",
											xlG7kue9w: "Contact us",
											xq26f_BEN:
												"Ready to create something extraordinary? Whether you're designing a dream home, a cutting-edge workplace, or a sustainable urban space, we\u2019re here to turn your ideas into reality.",
											...addPropertyOverrides3(
												{
													tSE9Czm1u: {
														gTy084auZ: resolvedLinks[1],
														variant: "YCrTzZbk9",
													},
													VScSZyOaR: {
														gTy084auZ: resolvedLinks[2],
														variant: "pn2aGgou5",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-J5ZEz.framer-1x72hi8, .framer-J5ZEz .framer-1x72hi8 { display: block; }",
	".framer-J5ZEz.framer-lq1iae { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 0px 100px 0px; position: relative; width: 1200px; }",
	".framer-J5ZEz .framer-1jrrzjx-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-J5ZEz.framer-v-1eacoaa.framer-lq1iae { padding: 80px 0px 80px 0px; width: 810px; }",
	".framer-J5ZEz.framer-v-19yr4ub.framer-lq1iae { padding: 60px 0px 60px 0px; width: 390px; }",
];
var FramerMFLZMQtsg = withCSS3(Component3, css6, "framer-J5ZEz");
var stdin_default3 = FramerMFLZMQtsg;
FramerMFLZMQtsg.displayName = "CTA";
FramerMFLZMQtsg.defaultProps = {
	height: 867,
	width: 1200,
};
addPropertyControls3(FramerMFLZMQtsg, {
	variant: {
		options: ["RxBB4n2Nx", "tSE9Czm1u", "VScSZyOaR"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts3(
	FramerMFLZMQtsg,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SectionCTAFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VScSZyOaR",
	md: "tSE9Czm1u",
	xl: "RxBB4n2Nx",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var cta_default = ComponentWithRoot;
export { cta_default as default };
