// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * textColor?: string // Text Color
}} Props

 */
import {
	stdin_default as stdin_default3,
	stdin_default2 as stdin_default4,
} from "./chunks/chunk-XXQODGWC.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-VCZFCYX7.js";
import "./chunks/chunk-BTSBQWPZ.js";
import "./chunks/chunk-4LLJ7Y3K.js";
import { stdin_default } from "./chunks/chunk-UNQN4VUP.js";
import "./chunks/chunk-IICRMQVR.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:navbar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/NAVBAR-Dgn6.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MiscLogoFonts = getFonts(stdin_default4);
var ButtonMenuFonts = getFonts(stdin_default2);
var ButtonSearchFonts = getFonts(stdin_default3);
var ButtonPrimaryFonts = getFonts(stdin_default);
var serializationHash = "framer-vpa4p";
var variantClassNames = {
	mgW6tFgYC: "framer-v-d9hw3d",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, textColor, width, ...props }) => {
	return {
		...props,
		QMt9cTb7J:
			textColor ??
			props.QMt9cTb7J ??
			"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		QMt9cTb7J,
		ojkG4qQavgwVi4QB11,
		j3CchF9t5gwVi4QB11,
		EOVNsc42UgwVi4QB11,
		pP3Nd92E8gwVi4QB11,
		iwk7G6PyWgwVi4QB11,
		ES3Bak9WKgwVi4QB11,
		Gso7DTzUqgwVi4QB11,
		AaFV7vb6cgwVi4QB11,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "mgW6tFgYC",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-d9hw3d",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"mgW6tFgYC"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-ls0gle"}
							data-framer-name={"Logo + Action"}
							layoutDependency={layoutDependency}
							layoutId={"ls703XbQP"}
						>
							<ComponentViewportProvider
								height={25}
								width={"62px"}
								y={
									(componentViewport?.y || 0) +
									(0 + ((componentViewport?.height || 34) - 0 - 25) / 2) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-17d4daq-container"}
									layoutDependency={layoutDependency}
									layoutId={"iVRb3_5zc-container"}
									nodeId={"iVRb3_5zc"}
									rendersWithMotion={true}
									scopeId={"gk7Fjcsw6"}
								>
									{_jsx(stdin_default4, {
										height: "100%",
										id: "iVRb3_5zc",
										layoutId: "iVRb3_5zc",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: ojkG4qQavgwVi4QB11,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						<motion.nav
							className={"framer-8fs7ge"}
							data-framer-name={"Navigation"}
							layoutDependency={layoutDependency}
							layoutId={"iyPx0zGgm"}
						>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "augiA20Il",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider
										height={16}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 34) - 0 - 16) / 2) +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1s0mpxc-container"}
											layoutDependency={layoutDependency}
											layoutId={"ho6_R0OGS-container"}
											nodeId={"ho6_R0OGS"}
											rendersWithMotion={true}
											scopeId={"gk7Fjcsw6"}
										>
											{_jsx(stdin_default2, {
												ccL75Jviw: resolvedLinks[0],
												height: "100%",
												id: "ho6_R0OGS",
												layoutId: "ho6_R0OGS",
												RoZ80uGGd: QMt9cTb7J,
												uIJ76_ZdU: "Startseite",
												variant: j3CchF9t5gwVi4QB11,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "RmdKiVesO",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks1) => (
									<ComponentViewportProvider
										height={16}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 34) - 0 - 16) / 2) +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-12fpspo-container"}
											layoutDependency={layoutDependency}
											layoutId={"zSZIm5ORB-container"}
											nodeId={"zSZIm5ORB"}
											rendersWithMotion={true}
											scopeId={"gk7Fjcsw6"}
										>
											{_jsx(stdin_default2, {
												ccL75Jviw: resolvedLinks1[0],
												height: "100%",
												id: "zSZIm5ORB",
												layoutId: "zSZIm5ORB",
												RoZ80uGGd: QMt9cTb7J,
												uIJ76_ZdU: "About",
												variant: EOVNsc42UgwVi4QB11,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "TpyOCMB_G",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks2) => (
									<ComponentViewportProvider
										height={16}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 34) - 0 - 16) / 2) +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-12lcwjb-container"}
											layoutDependency={layoutDependency}
											layoutId={"mNU9SbejT-container"}
											nodeId={"mNU9SbejT"}
											rendersWithMotion={true}
											scopeId={"gk7Fjcsw6"}
										>
											{_jsx(stdin_default2, {
												ccL75Jviw: resolvedLinks2[0],
												height: "100%",
												id: "mNU9SbejT",
												layoutId: "mNU9SbejT",
												RoZ80uGGd: QMt9cTb7J,
												uIJ76_ZdU: "Services",
												variant: pP3Nd92E8gwVi4QB11,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "wwtpvR9H7",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks3) => (
									<ComponentViewportProvider
										height={16}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 34) - 0 - 16) / 2) +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1duvd6b-container"}
											layoutDependency={layoutDependency}
											layoutId={"t1cM0CiSM-container"}
											nodeId={"t1cM0CiSM"}
											rendersWithMotion={true}
											scopeId={"gk7Fjcsw6"}
										>
											{_jsx(stdin_default2, {
												ccL75Jviw: resolvedLinks3[0],
												height: "100%",
												id: "t1cM0CiSM",
												layoutId: "t1cM0CiSM",
												RoZ80uGGd: QMt9cTb7J,
												uIJ76_ZdU: "Projects",
												variant: iwk7G6PyWgwVi4QB11,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "i2kvab7hr",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks4) => (
									<ComponentViewportProvider
										height={16}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 34) - 0 - 16) / 2) +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1vr5eub-container"}
											layoutDependency={layoutDependency}
											layoutId={"JP4iWj7uP-container"}
											nodeId={"JP4iWj7uP"}
											rendersWithMotion={true}
											scopeId={"gk7Fjcsw6"}
										>
											{_jsx(stdin_default2, {
												ccL75Jviw: resolvedLinks4[0],
												height: "100%",
												id: "JP4iWj7uP",
												layoutId: "JP4iWj7uP",
												RoZ80uGGd: QMt9cTb7J,
												uIJ76_ZdU: "Blog",
												variant: ES3Bak9WKgwVi4QB11,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "WOrYUhfBH",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks5) => (
									<ComponentViewportProvider
										height={16}
										y={
											(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 34) - 0 - 16) / 2) +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-w30xy1-container"}
											layoutDependency={layoutDependency}
											layoutId={"e7VqSiLxL-container"}
											nodeId={"e7VqSiLxL"}
											rendersWithMotion={true}
											scopeId={"gk7Fjcsw6"}
										>
											{_jsx(stdin_default2, {
												ccL75Jviw: resolvedLinks5[0],
												height: "100%",
												id: "e7VqSiLxL",
												layoutId: "e7VqSiLxL",
												RoZ80uGGd: QMt9cTb7J,
												uIJ76_ZdU: "Contact",
												variant: Gso7DTzUqgwVi4QB11,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
						</motion.nav>
						<motion.div
							className={"framer-vsrz3h"}
							data-framer-name={"Action"}
							layoutDependency={layoutDependency}
							layoutId={"AtFLNoyNO"}
						>
							<ComponentViewportProvider
								height={34}
								y={
									(componentViewport?.y || 0) +
									(0 + ((componentViewport?.height || 34) - 0 - 34) / 2) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-16ko3oj-container"}
									layoutDependency={layoutDependency}
									layoutId={"ny4mdw9GY-container"}
									nodeId={"ny4mdw9GY"}
									rendersWithMotion={true}
									scopeId={"gk7Fjcsw6"}
								>
									{_jsx(stdin_default3, {
										bdY7mewUZ: QMt9cTb7J,
										height: "100%",
										id: "ny4mdw9GY",
										layoutId: "ny4mdw9GY",
										variant: "SNIsJCBAl",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={33}
								y={
									(componentViewport?.y || 0) +
									(0 + ((componentViewport?.height || 34) - 0 - 34) / 2) +
									0.5
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1w0gvcd-container"}
									layoutDependency={layoutDependency}
									layoutId={"LbT3cZhzs-container"}
									nodeId={"LbT3cZhzs"}
									rendersWithMotion={true}
									scopeId={"gk7Fjcsw6"}
								>
									{_jsx(stdin_default, {
										A1mdPRDCS: "Use template",
										height: "100%",
										id: "LbT3cZhzs",
										KKQ6Z0zNX: "https://marcframe.gumroad.com/l/titen",
										layoutId: "LbT3cZhzs",
										variant: AaFV7vb6cgwVi4QB11,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vpa4p.framer-1psgxfq, .framer-vpa4p .framer-1psgxfq { display: block; }",
	".framer-vpa4p.framer-d9hw3d { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
	".framer-vpa4p .framer-ls0gle { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-vpa4p .framer-17d4daq-container { aspect-ratio: 2.4615384615384617 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 26px); position: relative; width: 62px; }",
	".framer-vpa4p .framer-8fs7ge { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-vpa4p .framer-1s0mpxc-container, .framer-vpa4p .framer-12fpspo-container, .framer-vpa4p .framer-12lcwjb-container, .framer-vpa4p .framer-1duvd6b-container, .framer-vpa4p .framer-1vr5eub-container, .framer-vpa4p .framer-w30xy1-container, .framer-vpa4p .framer-16ko3oj-container, .framer-vpa4p .framer-1w0gvcd-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-vpa4p .framer-vsrz3h { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
];
var Framergk7Fjcsw6 = withCSS(Component, css, "framer-vpa4p");
var stdin_default5 = Framergk7Fjcsw6;
Framergk7Fjcsw6.displayName = "NAVBAR";
Framergk7Fjcsw6.defaultProps = {
	height: 34,
	width: 1100,
};
addPropertyControls(Framergk7Fjcsw6, {
	QMt9cTb7J: {
		defaultValue:
			'var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18)) /* {"name":"Black"} */',
		title: "Text Color",
		type: ControlType.Color,
	},
});
addFonts(
	Framergk7Fjcsw6,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...MiscLogoFonts,
		...ButtonMenuFonts,
		...ButtonSearchFonts,
		...ButtonPrimaryFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navbar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var navbar_default = ComponentWithRoot;
export { navbar_default as default };
