// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-63TWHLYQ.js";
import "./chunks/chunk-RNVUQTXT.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-ILVHS3C2.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-FYMJT4D6.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-4LLJ7Y3K.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-N4SVWGDY.js";
import { stdin_default } from "./chunks/chunk-UNQN4VUP.js";
import "./chunks/chunk-IICRMQVR.js";
import "./chunks/chunk-RZ6XIZ35.js";
import { className, css, fonts } from "./chunks/chunk-MBDBQ6CG.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-2RKPPYFD.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-6TWF3UWX.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:services
import { Fragment as Fragment6 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/SERVICES-UX9P.js
import { jsx as _jsx6, jsxs as _jsxs6 } from "react/jsx-runtime";
import {
	addFonts as addFonts5,
	addPropertyControls as addPropertyControls6,
	ComponentViewportProvider as ComponentViewportProvider4,
	ControlType as ControlType6,
	cx as cx5,
	getFonts as getFonts4,
	getFontsFromSharedStyle as getFontsFromSharedStyle4,
	getLoadingLazyAtYPosition,
	Image,
	ResolveLinks,
	RichText as RichText4,
	SmartComponentScopedContainer as SmartComponentScopedContainer4,
	useComponentViewport as useComponentViewport5,
	useLocaleInfo as useLocaleInfo5,
	useRouter,
	useVariantState as useVariantState5,
	withCSS as withCSS5,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup5,
	motion as motion6,
	MotionConfigContext as MotionConfigContext5,
} from "unframer";
import * as React5 from "react";
import { useRef as useRef5 } from "react";

// /:https://framerusercontent.com/modules/2eAe9cipllXf40lBqEdl/zGSoVNwrtOO6cEp1OG0N/CuRLjbvIQ.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/imwOMgFKgybAqXM65SWH/oOu6QBvBCZeWduuoC3HU/oasvV4O8C.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["UtaSLQQ89", "d8MWl6L2L"];
var serializationHash = "framer-mjN9C";
var variantClassNames = {
	d8MWl6L2L: "framer-v-8cyag2",
	UtaSLQQ89: "framer-v-iumzl2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "d8MWl6L2L",
	Open: "UtaSLQQ89",
};
var getProps = ({ click, description, height, id, title, width, ...props }) => {
	return {
		...props,
		KMtkXf8Vj: click ?? props.KMtkXf8Vj,
		MMzmcdNBo: title ?? props.MMzmcdNBo ?? "Sustainable Practices",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "UtaSLQQ89",
		z0q5HKaLx:
			description ??
			props.z0q5HKaLx ??
			"We integrate eco-friendly materials and energy-efficient solutions to create responsible, lasting architecture.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		MMzmcdNBo,
		z0q5HKaLx,
		KMtkXf8Vj,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "UtaSLQQ89",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap286xcm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (KMtkXf8Vj) {
			const res = await KMtkXf8Vj(...args);
			if (res === false) return false;
		}
		setVariant("d8MWl6L2L");
	});
	const onTaphjqsj5 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (KMtkXf8Vj) {
			const res = await KMtkXf8Vj(...args);
			if (res === false) return false;
		}
		setVariant("UtaSLQQ89");
	});
	const sharedStyleClassNames = [className7, className5];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "d8MWl6L2L") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-iumzl2",
							className8,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"UtaSLQQ89"}
						onTap={onTap286xcm}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-508cd75a-8f18-4393-92b6-c370a50e716c, rgba(18, 18, 18, 0.3))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								d8MWl6L2L: {
									"data-framer-name": "Close",
									onTap: onTaphjqsj5,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-dhe59s"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"ZyWJhX_rX"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-qo2647"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"LS4Qk86wo"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={MMzmcdNBo}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-15z4rdv"}
										data-styles-preset={"U1mraOJjt"}
									>
										{"Sustainable Practices"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-12w7u9o-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"o_jgCTUCO-container"}
									nodeId={"o_jgCTUCO"}
									rendersWithMotion={true}
									scopeId={"oasvV4O8C"}
									style={{
										rotate: 45,
									}}
									variants={{
										d8MWl6L2L: {
											rotate: 0,
										},
									}}
								>
									<Icon
										color={
											"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))"
										}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"Plus"}
										id={"o_jgCTUCO"}
										layoutId={"o_jgCTUCO"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"regular"}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1h5ou8i"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"CCG7DDGMg"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={z0q5HKaLx}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-144gy8o"}
										data-styles-preset={"qA7GDH1GX"}
									>
										{
											"We integrate eco-friendly materials and energy-efficient solutions to create responsible, lasting architecture."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mjN9C.framer-1t810wh, .framer-mjN9C .framer-1t810wh { display: block; }",
	".framer-mjN9C.framer-iumzl2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 0px 24px 0px; position: relative; width: 400px; }",
	".framer-mjN9C .framer-dhe59s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-mjN9C .framer-qo2647 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-mjN9C .framer-12w7u9o-container { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-mjN9C .framer-1h5ou8i { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css7,
	...css5,
	'.framer-mjN9C[data-border="true"]::after, .framer-mjN9C [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameroasvV4O8C = withCSS(Component, css8, "framer-mjN9C");
var stdin_default3 = FrameroasvV4O8C;
FrameroasvV4O8C.displayName = "Misc/Accordions";
FrameroasvV4O8C.defaultProps = {
	height: 155,
	width: 400,
};
addPropertyControls(FrameroasvV4O8C, {
	variant: {
		options: ["UtaSLQQ89", "d8MWl6L2L"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	MMzmcdNBo: {
		defaultValue: "Sustainable Practices",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	z0q5HKaLx: {
		defaultValue:
			"We integrate eco-friendly materials and energy-efficient solutions to create responsible, lasting architecture.",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	KMtkXf8Vj: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FrameroasvV4O8C,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/2eAe9cipllXf40lBqEdl/zGSoVNwrtOO6cEp1OG0N/CuRLjbvIQ.js
var MiscAccordionsFonts = getFonts2(stdin_default3);
var cycleOrder2 = [
	"T0AdKhzpN",
	"kqV8KQJCk",
	"Hn3u86bNS",
	"YUdEjbOJS",
	"DXSrYEbik",
];
var serializationHash2 = "framer-dQfRw";
var variantClassNames2 = {
	DXSrYEbik: "framer-v-1i9mu2h",
	Hn3u86bNS: "framer-v-1fpbq8w",
	kqV8KQJCk: "framer-v-1ligyh8",
	T0AdKhzpN: "framer-v-739ox",
	YUdEjbOJS: "framer-v-15als5y",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"01": "kqV8KQJCk",
	"02": "Hn3u86bNS",
	"03": "YUdEjbOJS",
	"04": "DXSrYEbik",
	"All Open": "T0AdKhzpN",
};
var getProps2 = ({
	description01,
	description02,
	description03,
	description04,
	height,
	id,
	title01,
	title02,
	title03,
	title04,
	width,
	...props
}) => {
	return {
		...props,
		aeJRtSyFf:
			description03 ??
			props.aeJRtSyFf ??
			"We integrate eco-friendly materials and energy-efficient solutions to create responsible, lasting architecture.",
		B1qaK7S3F: title04 ?? props.B1qaK7S3F ?? "Adaptability",
		FOQQnJpS_: title03 ?? props.FOQQnJpS_ ?? "Sustainable Practices",
		FYGJkI0QY: title02 ?? props.FYGJkI0QY ?? "Client-Centric Approach",
		QA8qOg8DS:
			description01 ??
			props.QA8qOg8DS ??
			"We push creative boundaries to deliver unique, forward-thinking architectural solutions.",
		ToFNsiDl0:
			description02 ??
			props.ToFNsiDl0 ??
			"Your vision is our priority\u2014we collaborate closely to ensure personalized, tailored designs.",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "T0AdKhzpN",
		XqUQgQcZw:
			description04 ??
			props.XqUQgQcZw ??
			"Our designs evolve with changing needs, ensuring flexibility and future-proof solutions.",
		yfnFsD0zv: title01 ?? props.yfnFsD0zv ?? "Innovative Design",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		yfnFsD0zv,
		QA8qOg8DS,
		FYGJkI0QY,
		ToFNsiDl0,
		FOQQnJpS_,
		aeJRtSyFf,
		B1qaK7S3F,
		XqUQgQcZw,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "T0AdKhzpN",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const KMtkXf8Vjzoiurn = activeVariantCallback(async (...args) => {
		setVariant("kqV8KQJCk");
	});
	const KMtkXf8Vj130y7t4 = activeVariantCallback(async (...args) => {
		setVariant("Hn3u86bNS");
	});
	const KMtkXf8Vj1olczti = activeVariantCallback(async (...args) => {
		setVariant("YUdEjbOJS");
	});
	const KMtkXf8Vjdcunh2 = activeVariantCallback(async (...args) => {
		setVariant("DXSrYEbik");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-739ox",
							className8,
							classNames,
						)}
						data-framer-name={"All Open"}
						layoutDependency={layoutDependency}
						layoutId={"T0AdKhzpN"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								DXSrYEbik: {
									"data-framer-name": "04",
								},
								Hn3u86bNS: {
									"data-framer-name": "02",
								},
								kqV8KQJCk: {
									"data-framer-name": "01",
								},
								YUdEjbOJS: {
									"data-framer-name": "03",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2
							height={155}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 576) - 0 - 620) / 2 + 0 + 0)
							}
							{...addPropertyOverrides2(
								{
									DXSrYEbik: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												0 +
												0),
									},
									Hn3u86bNS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 371) - 0 - 620) / 2 +
												0 +
												0),
									},
									kqV8KQJCk: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 349) - 0 - 620) / 2 +
												0 +
												0),
									},
									YUdEjbOJS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-1j3o1r5-container"}
								layoutDependency={layoutDependency}
								layoutId={"Mxqs6cunX-container"}
								nodeId={"Mxqs6cunX"}
								rendersWithMotion={true}
								scopeId={"CuRLjbvIQ"}
							>
								{_jsx2(stdin_default3, {
									height: "100%",
									id: "Mxqs6cunX",
									KMtkXf8Vj: KMtkXf8Vjzoiurn,
									layoutId: "Mxqs6cunX",
									MMzmcdNBo: yfnFsD0zv,
									style: {
										width: "100%",
									},
									variant: "UtaSLQQ89",
									width: "100%",
									z0q5HKaLx: QA8qOg8DS,
									...addPropertyOverrides2(
										{
											DXSrYEbik: {
												variant: "d8MWl6L2L",
											},
											Hn3u86bNS: {
												variant: "d8MWl6L2L",
											},
											YUdEjbOJS: {
												variant: "d8MWl6L2L",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={155}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 576) - 0 - 620) / 2 + 155 + 0)
							}
							{...addPropertyOverrides2(
								{
									DXSrYEbik: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												155 +
												0),
									},
									Hn3u86bNS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 371) - 0 - 620) / 2 +
												155 +
												0),
									},
									kqV8KQJCk: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 349) - 0 - 620) / 2 +
												155 +
												0),
									},
									YUdEjbOJS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												155 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-6ll6c3-container"}
								layoutDependency={layoutDependency}
								layoutId={"fgeCRGsMh-container"}
								nodeId={"fgeCRGsMh"}
								rendersWithMotion={true}
								scopeId={"CuRLjbvIQ"}
							>
								{_jsx2(stdin_default3, {
									height: "100%",
									id: "fgeCRGsMh",
									KMtkXf8Vj: KMtkXf8Vj130y7t4,
									layoutId: "fgeCRGsMh",
									MMzmcdNBo: FYGJkI0QY,
									style: {
										width: "100%",
									},
									variant: "UtaSLQQ89",
									width: "100%",
									z0q5HKaLx: ToFNsiDl0,
									...addPropertyOverrides2(
										{
											DXSrYEbik: {
												variant: "d8MWl6L2L",
											},
											kqV8KQJCk: {
												variant: "d8MWl6L2L",
											},
											YUdEjbOJS: {
												variant: "d8MWl6L2L",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={155}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 576) - 0 - 620) / 2 + 310 + 0)
							}
							{...addPropertyOverrides2(
								{
									DXSrYEbik: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												310 +
												0),
									},
									Hn3u86bNS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 371) - 0 - 620) / 2 +
												310 +
												0),
									},
									kqV8KQJCk: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 349) - 0 - 620) / 2 +
												310 +
												0),
									},
									YUdEjbOJS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												310 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-1w9zmhp-container"}
								layoutDependency={layoutDependency}
								layoutId={"axaZm4I8p-container"}
								nodeId={"axaZm4I8p"}
								rendersWithMotion={true}
								scopeId={"CuRLjbvIQ"}
							>
								{_jsx2(stdin_default3, {
									height: "100%",
									id: "axaZm4I8p",
									KMtkXf8Vj: KMtkXf8Vj1olczti,
									layoutId: "axaZm4I8p",
									MMzmcdNBo: FOQQnJpS_,
									style: {
										width: "100%",
									},
									variant: "UtaSLQQ89",
									width: "100%",
									z0q5HKaLx: aeJRtSyFf,
									...addPropertyOverrides2(
										{
											DXSrYEbik: {
												variant: "d8MWl6L2L",
											},
											Hn3u86bNS: {
												variant: "d8MWl6L2L",
											},
											kqV8KQJCk: {
												variant: "d8MWl6L2L",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={155}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 576) - 0 - 620) / 2 + 465 + 0)
							}
							{...addPropertyOverrides2(
								{
									DXSrYEbik: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												465 +
												0),
									},
									Hn3u86bNS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 371) - 0 - 620) / 2 +
												465 +
												0),
									},
									kqV8KQJCk: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 349) - 0 - 620) / 2 +
												465 +
												0),
									},
									YUdEjbOJS: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 620) / 2 +
												465 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-kbammk-container"}
								layoutDependency={layoutDependency}
								layoutId={"GpK8apraH-container"}
								nodeId={"GpK8apraH"}
								rendersWithMotion={true}
								scopeId={"CuRLjbvIQ"}
							>
								{_jsx2(stdin_default3, {
									height: "100%",
									id: "GpK8apraH",
									KMtkXf8Vj: KMtkXf8Vjdcunh2,
									layoutId: "GpK8apraH",
									MMzmcdNBo: B1qaK7S3F,
									style: {
										width: "100%",
									},
									variant: "UtaSLQQ89",
									width: "100%",
									z0q5HKaLx: XqUQgQcZw,
									...addPropertyOverrides2(
										{
											Hn3u86bNS: {
												variant: "d8MWl6L2L",
											},
											kqV8KQJCk: {
												variant: "d8MWl6L2L",
											},
											YUdEjbOJS: {
												variant: "d8MWl6L2L",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css9 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dQfRw.framer-1nb7df9, .framer-dQfRw .framer-1nb7df9 { display: block; }",
	".framer-dQfRw.framer-739ox { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 350px; }",
	".framer-dQfRw .framer-1j3o1r5-container, .framer-dQfRw .framer-6ll6c3-container, .framer-dQfRw .framer-1w9zmhp-container, .framer-dQfRw .framer-kbammk-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerCuRLjbvIQ = withCSS2(Component2, css9, "framer-dQfRw");
var stdin_default4 = FramerCuRLjbvIQ;
FramerCuRLjbvIQ.displayName = "Misc/Service Value";
FramerCuRLjbvIQ.defaultProps = {
	height: 576,
	width: 350,
};
addPropertyControls2(FramerCuRLjbvIQ, {
	variant: {
		options: ["T0AdKhzpN", "kqV8KQJCk", "Hn3u86bNS", "YUdEjbOJS", "DXSrYEbik"],
		optionTitles: ["All Open", "01", "02", "03", "04"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	yfnFsD0zv: {
		defaultValue: "Innovative Design",
		displayTextArea: false,
		title: "Title 01",
		type: ControlType2.String,
	},
	QA8qOg8DS: {
		defaultValue:
			"We push creative boundaries to deliver unique, forward-thinking architectural solutions.",
		displayTextArea: false,
		title: "Description 01",
		type: ControlType2.String,
	},
	FYGJkI0QY: {
		defaultValue: "Client-Centric Approach",
		displayTextArea: false,
		title: "Title 02",
		type: ControlType2.String,
	},
	ToFNsiDl0: {
		defaultValue:
			"Your vision is our priority\u2014we collaborate closely to ensure personalized, tailored designs.",
		displayTextArea: false,
		title: "Description 02",
		type: ControlType2.String,
	},
	FOQQnJpS_: {
		defaultValue: "Sustainable Practices",
		displayTextArea: false,
		title: "Title 03",
		type: ControlType2.String,
	},
	aeJRtSyFf: {
		defaultValue:
			"We integrate eco-friendly materials and energy-efficient solutions to create responsible, lasting architecture.",
		displayTextArea: false,
		title: "Description 03",
		type: ControlType2.String,
	},
	B1qaK7S3F: {
		defaultValue: "Adaptability",
		displayTextArea: false,
		title: "Title 04",
		type: ControlType2.String,
	},
	XqUQgQcZw: {
		defaultValue:
			"Our designs evolve with changing needs, ensuring flexibility and future-proof solutions.",
		displayTextArea: false,
		title: "Description 04",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerCuRLjbvIQ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...MiscAccordionsFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/SERVICES-UX9P.js
var ButtonPrimaryFonts = getFonts4(stdin_default);
var MotionDivWithFX = withFX(motion6.div);
var MiscServiceValue = stdin_default4;
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 18,
};
var transition2 = {
	damping: 55,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var Transition5 = ({ value, children }) => {
	const config = React5.useContext(MotionConfigContext5);
	const transition = value ?? config.transition;
	const contextValue = React5.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext5.Provider value={contextValue}>
			{children}
		</MotionConfigContext5.Provider>
	);
};
var Variants5 = motion6.create(React5.Fragment);
var humanReadableVariantMap3 = {
	Desktop: "l8whQih9a",
	Phone: "JU_XBdbLf",
	Tablet: "wdQbvkrFx",
};
var getProps5 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "l8whQih9a",
	};
};
var createLayoutDependency5 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component5 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const fallbackRef = useRef5(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React5.useId();
	const { activeLocale, setLocale } = useLocaleInfo5();
	const componentViewport = useComponentViewport5();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		...restProps
	} = getProps5(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState5({
		cycleOrder: ["l8whQih9a", "wdQbvkrFx", "JU_XBdbLf"],
		defaultVariant: "l8whQih9a",
		ref: refBinding,
		variant,
		variantClassNames: {
            JU_XBdbLf: "framer-v-u0qv0y",
            l8whQih9a: "framer-v-1nio7rc",
            wdQbvkrFx: "framer-v-197vd4y",
        },
	});
	const layoutDependency = createLayoutDependency5(props, variants);
	const sharedStyleClassNames = [className, className4, className2, className3];
	const scopingClassNames = cx5("framer-xbdWH", ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup5 id={layoutId ?? defaultLayoutId}>
			<Variants5 animate={variants} initial={false}>
				<Transition5 value={{
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
}}>
					<motion6.section
						{...restProps}
						{...gestureHandlers}
						className={cx5(
							scopingClassNames,
							"framer-1nio7rc",
							className8,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"l8whQih9a"}
						ref={refBinding}
						id="process"
						style={{
							...style,
						}}
						{...addPropertyOverrides5(
							{
								JU_XBdbLf: {
									"data-framer-name": "Phone",
								},
								wdQbvkrFx: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion6.div
							className={"framer-1wkkhf8"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"l_yqZ91Ia"}
						>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-nra19a"}
								data-framer-name={"Title Section"}
								layoutDependency={layoutDependency}
								layoutId={"ntcCIc6Bx"}
							>
								<motion6.div
									className={"framer-1bve2ih"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"i4BiJc_gf"}
								>
									<RichText4
										__fromCanvasComponent={true}
										className={"framer-1jn2rpc"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"VmSY0ZMV3"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion6.p
												className={"framer-styles-preset-11asbfe"}
												data-styles-preset={"NtXagAClV"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
												}}
											>
												{"So funktioniert's"}
											</motion6.p>
										</React5.Fragment>
									</RichText4>
									<RichText4
										__fromCanvasComponent={true}
										className={"framer-1sxujqk"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"FX6bvlUXG"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion6.h2
												className={"framer-styles-preset-rdnt0j"}
												data-styles-preset={"wIgsXR7Fc"}
											>
												{"In 4 Schritten zu Ihrer Denkmalimmobilie"}
											</motion6.h2>
										</React5.Fragment>
									</RichText4>
								</motion6.div>
							</MotionDivWithFX>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-m75gpm"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"BabrnzTc6"}
							>
								<ComponentViewportProvider4
									height={576}
									width={`max(min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) * 0.4091 - 48px, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(100 +
											((componentViewport?.height || 200) - 200 - 2544.4) / 2) +
										0 +
										330.4 +
										0
									}
								>
									<SmartComponentScopedContainer4
										className={"framer-pfo1j7-container"}
										layoutDependency={layoutDependency}
										layoutId={"Aqp6Oopzj-container"}
										nodeId={"Aqp6Oopzj"}
										rendersWithMotion={true}
										scopeId={"dKghMdWSg"}
									>
										<MiscServiceValue
											height="100%"
											id="Aqp6Oopzj"
											layoutId="Aqp6Oopzj"
											style={{ width: '100%' }}
											variant="kqV8KQJCk"
											width="100%"
											yfnFsD0zv="Schritt 1: Unverbindliches Erstgespräch"
											QA8qOg8DS="In einem ersten Gespräch lernen wir Ihre Wünsche und Ziele kennen und prüfen gemeinsam Ihre finanziellen Möglichkeiten. Dieser Schritt ist für Sie absolut kostenfrei und unverbindlich."
											FYGJkI0QY="Schritt 2: Individuelle Objektauswahl"
											ToFNsiDl0="Basierend auf Ihren Anforderungen suchen wir für Sie passende Denkmalimmobilien aus unserem Portfolio und stellen Ihnen diese detailliert vor."
											FOQQnJpS_="Schritt 3: Finanzierung und Notartermin"
											aeJRtSyFf="Wir unterstützen Sie bei der Finanzierungsplanung und begleiten Sie zum Notartermin, um den Kaufvertrag sicher abzuschließen."
											B1qaK7S3F="Schritt 4: Sanierung und Vermietung"
											XqUQgQcZw="Nach dem Kauf koordinieren wir die professionelle Sanierung Ihrer Immobilie und kümmern uns anschließend um die erfolgreiche Vermietung und Verwaltung."
										/>
									</SmartComponentScopedContainer4>
								</ComponentViewportProvider4>
							</MotionDivWithFX>
						</motion6.div>
					</motion6.section>
				</Transition5>
			</Variants5>
		</LayoutGroup5>
	);
});
var css12 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xbdWH.framer-1iu19uz, .framer-xbdWH .framer-1iu19uz { display: block; }",
	".framer-xbdWH.framer-1nio7rc { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-xbdWH .framer-1wkkhf8 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-xbdWH .framer-nra19a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-1bve2ih { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 750px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-1jn2rpc, .framer-xbdWH .framer-1sxujqk, .framer-xbdWH .framer-1fi8lcm, .framer-xbdWH .framer-dhoq9h, .framer-xbdWH .framer-lpi4wl, .framer-xbdWH .framer-1yxkrdy { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-xbdWH .framer-1mvaxxd { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-117oirn { flex: 1 0 0px; height: auto; max-width: 550px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-xbdWH .framer-o4d3ha-container, .framer-xbdWH .framer-ir5gz1-container, .framer-xbdWH .framer-3j4yel-container, .framer-xbdWH .framer-ezpsqs-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-xbdWH .framer-m75gpm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-1avd0nm { aspect-ratio: 1.4444444444444444 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 450px); overflow: hidden; position: relative; width: 59%; }",
	".framer-xbdWH .framer-pfo1j7-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-xbdWH.framer-v-197vd4y.framer-1nio7rc { padding: 80px 30px 80px 30px; width: 810px; }",
	".framer-xbdWH.framer-v-197vd4y .framer-1wkkhf8 { gap: 56px; }",
	".framer-xbdWH.framer-v-197vd4y .framer-1mvaxxd { gap: 100px; justify-content: center; }",
	".framer-xbdWH.framer-v-197vd4y .framer-117oirn { max-width: unset; }",
	".framer-xbdWH.framer-v-197vd4y .framer-1avd0nm { height: var(--framer-aspect-ratio-supported, 138px); }",
	".framer-xbdWH.framer-v-u0qv0y.framer-1nio7rc { padding: 60px 16px 60px 16px; width: 390px; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-1wkkhf8 { gap: 48px; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-1mvaxxd { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 48px; justify-content: center; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-m75gpm { flex-direction: column; gap: 32px; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-1avd0nm { height: var(--framer-aspect-ratio-supported, 138px); order: 1; width: 100%; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-pfo1j7-container { flex: none; order: 0; width: 100%; }",
	...css,
	...css4,
	...css2,
	...css3,
];
var FramerdKghMdWSg = withCSS5(Component5, css12, "framer-xbdWH");
var Process = FramerdKghMdWSg;
Process.displayName = "Process";
Process.defaultProps = {
	height: 2583,
	width: 1200,
};
addPropertyControls6(Process, {
	variant: {
		options: ["l8whQih9a", "wdQbvkrFx", "JU_XBdbLf"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType6.Enum,
	},
});
addFonts5(
	Process,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonPrimaryFonts,
		...getFontsFromSharedStyle4(fonts),
		...getFontsFromSharedStyle4(fonts4),
		...getFontsFromSharedStyle4(fonts2),
		...getFontsFromSharedStyle4(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:services
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JU_XBdbLf",
	md: "wdQbvkrFx",
	xl: "l8whQih9a",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(Process, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Process}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Process);
var process_default = ComponentWithRoot;
export { process_default as default };
