// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * category?: string // Category
 * projectCategory?: undefined // Project Category
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-EQ6EOYNA.js";
import {
	stdin_default as stdin_default2,
	stdin_default2 as stdin_default3,
	stdin_default3 as stdin_default4,
} from "./chunks/chunk-Q7H7SWYX.js";
import "./chunks/chunk-FYMJT4D6.js";
import "./chunks/chunk-4LLJ7Y3K.js";
import { stdin_default } from "./chunks/chunk-4F2TX32L.js";
import "./chunks/chunk-2RKPPYFD.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:project1
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/PROJECT1-RLnm.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	PathVariablesContext,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useQueryData,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CardProject02Fonts = getFonts(stdin_default4);
var CardProject01Fonts = getFonts(stdin_default3);
var cycleOrder = ["tLdDEawYD", "Td2ykYllN", "Sbh2K2cdt"];
var serializationHash = "framer-StudQ";
var variantClassNames = {
	Sbh2K2cdt: "framer-v-w55zs2",
	Td2ykYllN: "framer-v-1j1dl2e",
	tLdDEawYD: "framer-v-u1p587",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	filter: "blur(7px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	damping: 58,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0.3,
	tokenization: "word",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "tLdDEawYD",
	Phone: "Sbh2K2cdt",
	Tablet: "Td2ykYllN",
};
var getProps = ({ category, height, id, projectCategory, width, ...props }) => {
	return {
		...props,
		hFuPqMUHL: category ?? props.hFuPqMUHL ?? "Residential",
		LTEWlKbMr: projectCategory ?? props.LTEWlKbMr ?? "kJIzy7mAD",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "tLdDEawYD",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		hFuPqMUHL,
		LTEWlKbMr,
		SmHdARdOEEC5BU2Zku,
		Grw0eKwIcEC5BU2Zku,
		bbwOZ_kv_EC5BU2Zku,
		idEC5BU2Zku,
		SmHdARdOEHPBIGyOsm,
		Grw0eKwIcHPBIGyOsm,
		EPYNrHvbR_fMvHSufcMHPBIGyOsm,
		ijz0mlVW5HPBIGyOsm,
		MpsGV5tGNHPBIGyOsm,
		bbwOZ_kv_HPBIGyOsm,
		idHPBIGyOsm,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "tLdDEawYD",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-u1p587",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"tLdDEawYD"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Sbh2K2cdt: {
									"data-framer-name": "Phone",
								},
								Td2ykYllN: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-ko70my"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"KNOoPE4z6"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-2bt6fb"}
								effect={textEffect}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"OgOglUYlV"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={hFuPqMUHL}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-1n41l9y"}
										data-styles-preset={"YMmsPodJ4"}
									>
										{"Residential"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1jtsgu2"}
								data-framer-name={"Project List"}
								layoutDependency={layoutDependency}
								layoutId={"LQq0_uIUj"}
							>
								<motion.div
									className={"framer-1n3nkxf"}
									data-framer-name={"Featured"}
									layoutDependency={layoutDependency}
									layoutId={"EC5BU2Zku"}
								>
									<ChildrenCanSuspend>
										<QueryData
											query={{
												from: {
													constraint: {
														left: {
															collection: "EC5BU2Zku",
															name: "EPYNrHvbR",
															type: "Identifier",
														},
														operator: "==",
														right: {
															collection: "EPYNrHvbR",
															name: "id",
															type: "Identifier",
														},
														type: "BinaryOperation",
													},
													left: {
														alias: "EC5BU2Zku",
														data: stdin_default,
														type: "Collection",
													},
													right: {
														alias: "EPYNrHvbR",
														data: stdin_default2,
														type: "Collection",
													},
													type: "LeftJoin",
												},
												limit: {
													type: "LiteralValue",
													value: 1,
												},
												offset: {
													type: "LiteralValue",
													value: 0,
												},
												select: [
													{
														collection: "EC5BU2Zku",
														name: "SmHdARdOE",
														type: "Identifier",
													},
													{
														collection: "EC5BU2Zku",
														name: "Grw0eKwIc",
														type: "Identifier",
													},
													{
														collection: "EC5BU2Zku",
														name: "bbwOZ_kv_",
														type: "Identifier",
													},
													{
														collection: "EC5BU2Zku",
														name: "id",
														type: "Identifier",
													},
												],
												where: {
													left: {
														collection: "EPYNrHvbR",
														name: "id",
														type: "Identifier",
													},
													operator: "==",
													right: {
														type: "LiteralValue",
														value: LTEWlKbMr,
													},
													type: "BinaryOperation",
												},
											}}
										>
											{(collection, paginationInfo, loadMore) => (
												<_Fragment>
													{collection?.map(
														(
															{
																bbwOZ_kv_: bbwOZ_kv_EC5BU2Zku2,
																Grw0eKwIc: Grw0eKwIcEC5BU2Zku2,
																id: idEC5BU2Zku2,
																SmHdARdOE: SmHdARdOEEC5BU2Zku2,
															},
															index,
														) => {
															SmHdARdOEEC5BU2Zku2 ??= "";
															Grw0eKwIcEC5BU2Zku2 ??= "";
															bbwOZ_kv_EC5BU2Zku2 ??= "";
															return (
																<LayoutGroup key={idEC5BU2Zku2} id={`EC5BU2Zku-${idEC5BU2Zku2}`}>
																	<PathVariablesContext.Provider
																		value={{
																			bbwOZ_kv_: bbwOZ_kv_EC5BU2Zku2,
																		}}
																	>
																		<ResolveLinks
																			links={[
																				{
																					href: {
																						pathVariables: {
																							bbwOZ_kv_: bbwOZ_kv_EC5BU2Zku2,
																						},
																						webPageId: "ui9hfjwfv",
																					},
																					implicitPathVariables: void 0,
																				},
																				{
																					href: {
																						pathVariables: {
																							bbwOZ_kv_: bbwOZ_kv_EC5BU2Zku2,
																						},
																						webPageId: "ui9hfjwfv",
																					},
																					implicitPathVariables: void 0,
																				},
																				{
																					href: {
																						pathVariables: {
																							bbwOZ_kv_: bbwOZ_kv_EC5BU2Zku2,
																						},
																						webPageId: "ui9hfjwfv",
																					},
																					implicitPathVariables: void 0,
																				},
																			]}
																		>
																			{(resolvedLinks) => (
																				<ComponentViewportProvider
																					height={600}
																					width={`min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px)`}
																					y={
																						(componentViewport?.y || 0) +
																						(50 +
																							((componentViewport?.height ||
																								200) -
																								150 -
																								1284.2) /
																								2) +
																						0 +
																						131.2 +
																						0 +
																						0 +
																						0 +
																						0
																					}
																					{...addPropertyOverrides(
																						{
																							Sbh2K2cdt: {
																								width: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
																								y:
																									(componentViewport?.y || 0) +
																									(30 +
																										((componentViewport?.height ||
																											200) -
																											90 -
																											1244.2) /
																											2) +
																									0 +
																									115.2 +
																									0 +
																									0 +
																									0 +
																									0,
																							},
																							Td2ykYllN: {
																								width: `min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px)`,
																								y:
																									(componentViewport?.y || 0) +
																									(40 +
																										((componentViewport?.height ||
																											200) -
																											120 -
																											1260.2) /
																											2) +
																									0 +
																									123.2 +
																									0 +
																									0 +
																									0 +
																									0,
																							},
																						},
																						baseVariant,
																						gestureVariant,
																					)}
																				>
																					<SmartComponentScopedContainer
																						className={
																							"framer-m2hkg0-container"
																						}
																						layoutDependency={layoutDependency}
																						layoutId={"G_F8hdLBs-container"}
																						nodeId={"G_F8hdLBs"}
																						rendersWithMotion={true}
																						scopeId={"UQ8esVMHi"}
																					>
																						{_jsx(stdin_default4, {
																							eon37CiyT: Grw0eKwIcEC5BU2Zku2,
																							height: "100%",
																							id: "G_F8hdLBs",
																							layoutId: "G_F8hdLBs",
																							SJqK42bRM: resolvedLinks[0],
																							style: {
																								height: "100%",
																								width: "100%",
																							},
																							variant: "QbSi_Oief",
																							width: "100%",
																							Xqbaq21IL: SmHdARdOEEC5BU2Zku2,
																							...addPropertyOverrides(
																								{
																									Sbh2K2cdt: {
																										SJqK42bRM: resolvedLinks[2],
																										variant: "UX1ufNKZE",
																									},
																									Td2ykYllN: {
																										SJqK42bRM: resolvedLinks[1],
																										variant: "t86aS_Wy3",
																									},
																								},
																								baseVariant,
																								gestureVariant,
																							),
																						})}
																					</SmartComponentScopedContainer>
																				</ComponentViewportProvider>
																			)}
																		</ResolveLinks>
																	</PathVariablesContext.Provider>
																</LayoutGroup>
															);
														},
													)}
												</_Fragment>
											)}
										</QueryData>
									</ChildrenCanSuspend>
								</motion.div>
								<motion.div
									className={"framer-147tu2r"}
									layoutDependency={layoutDependency}
									layoutId={"HPBIGyOsm"}
								>
									<ChildrenCanSuspend>
										<QueryData
											query={{
												from: {
													constraint: {
														left: {
															collection: "HPBIGyOsm",
															name: "EPYNrHvbR",
															type: "Identifier",
														},
														operator: "==",
														right: {
															collection: "EPYNrHvbR",
															name: "id",
															type: "Identifier",
														},
														type: "BinaryOperation",
													},
													left: {
														alias: "HPBIGyOsm",
														data: stdin_default,
														type: "Collection",
													},
													right: {
														alias: "EPYNrHvbR",
														data: stdin_default2,
														type: "Collection",
													},
													type: "LeftJoin",
												},
												offset: {
													type: "LiteralValue",
													value: 1,
												},
												select: [
													{
														collection: "HPBIGyOsm",
														name: "SmHdARdOE",
														type: "Identifier",
													},
													{
														collection: "HPBIGyOsm",
														name: "Grw0eKwIc",
														type: "Identifier",
													},
													{
														alias: "EPYNrHvbR.fMvHSufcM",
														collection: "EPYNrHvbR",
														name: "fMvHSufcM",
														type: "Identifier",
													},
													{
														collection: "HPBIGyOsm",
														name: "ijz0mlVW5",
														type: "Identifier",
													},
													{
														collection: "HPBIGyOsm",
														name: "MpsGV5tGN",
														type: "Identifier",
													},
													{
														collection: "HPBIGyOsm",
														name: "bbwOZ_kv_",
														type: "Identifier",
													},
													{
														collection: "HPBIGyOsm",
														name: "id",
														type: "Identifier",
													},
												],
												where: {
													left: {
														collection: "EPYNrHvbR",
														name: "id",
														type: "Identifier",
													},
													operator: "==",
													right: {
														type: "LiteralValue",
														value: LTEWlKbMr,
													},
													type: "BinaryOperation",
												},
											}}
										>
											{(collection1, paginationInfo1, loadMore1) => (
												<_Fragment>
													{collection1?.map(
														(
															{
																"EPYNrHvbR.fMvHSufcM":
																	EPYNrHvbR_fMvHSufcMHPBIGyOsm2,
																bbwOZ_kv_: bbwOZ_kv_HPBIGyOsm2,
																Grw0eKwIc: Grw0eKwIcHPBIGyOsm2,
																id: idHPBIGyOsm2,
																ijz0mlVW5: ijz0mlVW5HPBIGyOsm2,
																MpsGV5tGN: MpsGV5tGNHPBIGyOsm2,
																SmHdARdOE: SmHdARdOEHPBIGyOsm2,
															},
															index1,
														) => {
															SmHdARdOEHPBIGyOsm2 ??= "";
															Grw0eKwIcHPBIGyOsm2 ??= "";
															EPYNrHvbR_fMvHSufcMHPBIGyOsm2 ??= "";
															ijz0mlVW5HPBIGyOsm2 ??= "";
															bbwOZ_kv_HPBIGyOsm2 ??= "";
															return (
																<LayoutGroup key={idHPBIGyOsm2} id={`HPBIGyOsm-${idHPBIGyOsm2}`}>
																	<PathVariablesContext.Provider
																		value={{
																			bbwOZ_kv_: bbwOZ_kv_HPBIGyOsm2,
																		}}
																	>
																		<ResolveLinks
																			links={[
																				{
																					href: {
																						pathVariables: {
																							bbwOZ_kv_: bbwOZ_kv_HPBIGyOsm2,
																						},
																						webPageId: "ui9hfjwfv",
																					},
																					implicitPathVariables: void 0,
																				},
																				{
																					href: {
																						pathVariables: {
																							bbwOZ_kv_: bbwOZ_kv_HPBIGyOsm2,
																						},
																						webPageId: "ui9hfjwfv",
																					},
																					implicitPathVariables: void 0,
																				},
																				{
																					href: {
																						pathVariables: {
																							bbwOZ_kv_: bbwOZ_kv_HPBIGyOsm2,
																						},
																						webPageId: "ui9hfjwfv",
																					},
																					implicitPathVariables: void 0,
																				},
																			]}
																		>
																			{(resolvedLinks1) => (
																				<ComponentViewportProvider
																					height={481}
																					width={`max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 48px) / 3, 50px)`}
																					y={
																						(componentViewport?.y || 0) +
																						(50 +
																							((componentViewport?.height ||
																								200) -
																								150 -
																								1284.2) /
																								2) +
																						0 +
																						131.2 +
																						0 +
																						648 +
																						0 +
																						0
																					}
																					{...addPropertyOverrides(
																						{
																							Sbh2K2cdt: {
																								width: `max(min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px), 50px)`,
																								y:
																									(componentViewport?.y || 0) +
																									(30 +
																										((componentViewport?.height ||
																											200) -
																											90 -
																											1244.2) /
																											2) +
																									0 +
																									115.2 +
																									0 +
																									624 +
																									0 +
																									0,
																							},
																							Td2ykYllN: {
																								width: `max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) - 24px) / 2, 50px)`,
																								y:
																									(componentViewport?.y || 0) +
																									(40 +
																										((componentViewport?.height ||
																											200) -
																											120 -
																											1260.2) /
																											2) +
																									0 +
																									123.2 +
																									0 +
																									632 +
																									0 +
																									0,
																							},
																						},
																						baseVariant,
																						gestureVariant,
																					)}
																				>
																					<SmartComponentScopedContainer
																						className={
																							"framer-ljrrir-container"
																						}
																						layoutDependency={layoutDependency}
																						layoutId={"c3z8teSOv-container"}
																						nodeId={"c3z8teSOv"}
																						rendersWithMotion={true}
																						scopeId={"UQ8esVMHi"}
																					>
																						{_jsx(stdin_default3, {
																							height: "100%",
																							id: "c3z8teSOv",
																							KzzSC31rK: SmHdARdOEHPBIGyOsm2,
																							L0P95UTa0: ijz0mlVW5HPBIGyOsm2,
																							layoutId: "c3z8teSOv",
																							OGGzrLg2s: Grw0eKwIcHPBIGyOsm2,
																							rqU6RVk2j:
																								EPYNrHvbR_fMvHSufcMHPBIGyOsm2,
																							sD9rBGBaZ: resolvedLinks1[0],
																							style: {
																								width: "100%",
																							},
																							SXqQY7jK_:
																								toResponsiveImage(
																									MpsGV5tGNHPBIGyOsm2,
																								),
																							variant: "pSncNt0Xw",
																							width: "100%",
																							...addPropertyOverrides(
																								{
																									Sbh2K2cdt: {
																										sD9rBGBaZ:
																											resolvedLinks1[2],
																									},
																									Td2ykYllN: {
																										sD9rBGBaZ:
																											resolvedLinks1[1],
																									},
																								},
																								baseVariant,
																								gestureVariant,
																							),
																						})}
																					</SmartComponentScopedContainer>
																				</ComponentViewportProvider>
																			)}
																		</ResolveLinks>
																	</PathVariablesContext.Provider>
																</LayoutGroup>
															);
														},
													)}
												</_Fragment>
											)}
										</QueryData>
									</ChildrenCanSuspend>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-StudQ.framer-w37trt, .framer-StudQ .framer-w37trt { display: block; }",
	".framer-StudQ.framer-u1p587 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 50px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-StudQ .framer-ko70my { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-StudQ .framer-2bt6fb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-StudQ .framer-1jtsgu2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-StudQ .framer-1n3nkxf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-StudQ .framer-m2hkg0-container { aspect-ratio: 1.8333333333333333 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 600px); position: relative; width: 100%; }",
	".framer-StudQ .framer-147tu2r { display: grid; flex: none; gap: 24px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-StudQ .framer-ljrrir-container { align-self: start; flex: none; height: auto; justify-self: start; position: relative; width: 100%; }",
	".framer-StudQ.framer-v-1j1dl2e.framer-u1p587 { padding: 40px 30px 80px 30px; width: 810px; }",
	".framer-StudQ.framer-v-1j1dl2e .framer-ko70my { gap: 56px; }",
	".framer-StudQ.framer-v-1j1dl2e .framer-1jtsgu2 { gap: 32px; }",
	".framer-StudQ.framer-v-1j1dl2e .framer-m2hkg0-container, .framer-StudQ.framer-v-w55zs2 .framer-m2hkg0-container { height: var(--framer-aspect-ratio-supported, 109px); }",
	".framer-StudQ.framer-v-1j1dl2e .framer-147tu2r { grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-StudQ.framer-v-w55zs2.framer-u1p587 { padding: 30px 16px 60px 16px; width: 200px; }",
	".framer-StudQ.framer-v-w55zs2 .framer-ko70my { gap: 48px; }",
	".framer-StudQ.framer-v-w55zs2 .framer-1jtsgu2 { gap: 24px; }",
	".framer-StudQ.framer-v-w55zs2 .framer-147tu2r { grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	...css,
];
var FramerUQ8esVMHi = withCSS(Component, css2, "framer-StudQ");
var stdin_default5 = FramerUQ8esVMHi;
FramerUQ8esVMHi.displayName = "PROJECT1";
FramerUQ8esVMHi.defaultProps = {
	height: 1277,
	width: 1200,
};
addPropertyControls(FramerUQ8esVMHi, {
	variant: {
		options: ["tLdDEawYD", "Td2ykYllN", "Sbh2K2cdt"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	hFuPqMUHL: {
		defaultValue: "Residential",
		title: "Category",
		type: ControlType.String,
	},
	LTEWlKbMr: {
		dataIdentifier: "local-module:collection/ZKNI0G_36:default",
		defaultValue: "kJIzy7mAD",
		title: "Project Category",
		type: ControlType.CollectionReference,
	},
});
addFonts(
	FramerUQ8esVMHi,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CardProject02Fonts,
		...CardProject01Fonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:project1
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Sbh2K2cdt",
	md: "Td2ykYllN",
	xl: "tLdDEawYD",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Project1FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var project1_default = ComponentWithRoot;
export { project1_default as default };
