// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-N4SVWGDY.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-4F2TX32L.js";
import { stdin_default } from "./chunks/chunk-UNQN4VUP.js";
import "./chunks/chunk-IICRMQVR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6TWF3UWX.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:services2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/SERVICES2-yzSw.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	PathVariablesContext,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useQueryData,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ButtonPrimaryFonts = getFonts(stdin_default);
var cycleOrder = ["YpsE4EfXY", "moNzV090n", "TDK1WYV5h"];
var serializationHash = "framer-zdhhX";
var variantClassNames = {
	moNzV090n: "framer-v-13u1434",
	TDK1WYV5h: "framer-v-1x8wx0r",
	YpsE4EfXY: "framer-v-o6v2mw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "YpsE4EfXY",
	Phone: "TDK1WYV5h",
	Tablet: "moNzV090n",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "YpsE4EfXY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		MpsGV5tGNFZab8E2zL,
		bbwOZ_kv_FZab8E2zL,
		idFZab8E2zL,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YpsE4EfXY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-o6v2mw",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"YpsE4EfXY"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								moNzV090n: {
									"data-framer-name": "Tablet",
								},
								TDK1WYV5h: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1xxfotg"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"Em4UXwZcr"}
						>
							<motion.div
								className={"framer-1oqg25v"}
								layoutDependency={layoutDependency}
								layoutId={"FZab8E2zL"}
							>
								<ChildrenCanSuspend>
									<QueryData
										query={{
											from: {
												alias: "FZab8E2zL",
												data: stdin_default2,
												type: "Collection",
											},
											limit: {
												type: "LiteralValue",
												value: 6,
											},
											select: [
												{
													collection: "FZab8E2zL",
													name: "MpsGV5tGN",
													type: "Identifier",
												},
												{
													collection: "FZab8E2zL",
													name: "bbwOZ_kv_",
													type: "Identifier",
												},
												{
													collection: "FZab8E2zL",
													name: "id",
													type: "Identifier",
												},
											],
										}}
									>
										{(collection, paginationInfo, loadMore) => (
											<_Fragment>
												{collection?.map(
													(
														{
															bbwOZ_kv_: bbwOZ_kv_FZab8E2zL2,
															id: idFZab8E2zL2,
															MpsGV5tGN: MpsGV5tGNFZab8E2zL2,
														},
														index,
													) => {
														bbwOZ_kv_FZab8E2zL2 ??= "";
														return (
															<LayoutGroup id={`FZab8E2zL-${idFZab8E2zL2}`}>
																<PathVariablesContext.Provider
																	value={{
																		bbwOZ_kv_: bbwOZ_kv_FZab8E2zL2,
																	}}
																>
																	<motion.div
																		className={"framer-16zeecp"}
																		layoutDependency={layoutDependency}
																		layoutId={"xzwe5uu6p"}
																	>
																		<Image
																			background={{
																				alt: "",
																				fit: "fill",
																				loading: getLoadingLazyAtYPosition(
																					(componentViewport?.y || 0) +
																						(100 +
																							((componentViewport?.height ||
																								200) -
																								200 -
																								231.4) /
																								2) +
																						79.7 +
																						0 +
																						0 +
																						0,
																				),
																				sizes: `max(max((max((min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) - 80px) / 2, 1px) - 24px) / 3, 50px), 1px)`,
																				...toResponsiveImage(
																					MpsGV5tGNFZab8E2zL2,
																				),
																			}}
																			className={"framer-1oiwg61"}
																			layoutDependency={layoutDependency}
																			layoutId={"kMqXOyU9v"}
																			{...addPropertyOverrides(
																				{
																					moNzV090n: {
																						background: {
																							alt: "",
																							fit: "fill",
																							loading:
																								getLoadingLazyAtYPosition(
																									(componentViewport?.y || 0) +
																										(80 +
																											((componentViewport?.height ||
																												200) -
																												160 -
																												231.4) /
																												2) +
																										94.7 +
																										0 +
																										0 +
																										0,
																								),
																							sizes: `max(max((max((min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) - 48px) / 2, 1px) - 24px) / 3, 50px), 1px)`,
																							...toResponsiveImage(
																								MpsGV5tGNFZab8E2zL2,
																							),
																						},
																					},
																					TDK1WYV5h: {
																						background: {
																							alt: "",
																							fit: "fill",
																							loading:
																								getLoadingLazyAtYPosition(
																									(componentViewport?.y || 0) +
																										(60 +
																											((componentViewport?.height ||
																												200) -
																												120 -
																												321.4) /
																												2) +
																										0 +
																										0 +
																										0 +
																										0 +
																										0,
																								),
																							sizes: `max(max((min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px) - 24px) / 3, 50px), 1px)`,
																							...toResponsiveImage(
																								MpsGV5tGNFZab8E2zL2,
																							),
																						},
																					},
																				},
																				baseVariant,
																				gestureVariant,
																			)}
																		/>
																	</motion.div>
																</PathVariablesContext.Provider>
															</LayoutGroup>
														);
													},
												)}
											</_Fragment>
										)}
									</QueryData>
								</ChildrenCanSuspend>
							</motion.div>
							<motion.div
								className={"framer-4ma0pe"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"kvOMfCAMk"}
							>
								<motion.div
									className={"framer-wjfqrh"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"XfNG3OvOQ"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-7d874b"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ZiA7MdUP5"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h2
												className={"framer-styles-preset-rdnt0j"}
												data-styles-preset={"wIgsXR7Fc"}
											>
												{"Start Your Dream Project Today"}
											</motion.h2>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-109skd4"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ZYX0x5DcG"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-144gy8o"}
												data-styles-preset={"qA7GDH1GX"}
											>
												{
													"Whether you\u2019re envisioning a custom home, a commercial space, or a major renovation, our team of experienced professionals is here to guide you every step of the way. With a commitment to quality, innovation, & client satisfaction."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "WOrYUhfBH",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "WOrYUhfBH",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "WOrYUhfBH",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider
											height={33}
											y={
												(componentViewport?.y || 0) +
												(100 +
													((componentViewport?.height || 200) - 200 - 231.4) /
														2) +
												0 +
												0 +
												198.4
											}
											{...addPropertyOverrides(
												{
													moNzV090n: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	160 -
																	231.4) /
																	2) +
															0 +
															0 +
															198.4,
													},
													TDK1WYV5h: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	120 -
																	321.4) /
																	2) +
															0 +
															90 +
															0 +
															198.4,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1h7amsi-container"}
												layoutDependency={layoutDependency}
												layoutId={"icNvsP0hS-container"}
												nodeId={"icNvsP0hS"}
												rendersWithMotion={true}
												scopeId={"OxccbqJmn"}
											>
												{_jsx(stdin_default, {
													A1mdPRDCS: "Contact us",
													height: "100%",
													id: "icNvsP0hS",
													KKQ6Z0zNX: resolvedLinks[0],
													layoutId: "icNvsP0hS",
													variant: "GQY9EfGY4",
													width: "100%",
													...addPropertyOverrides(
														{
															moNzV090n: {
																KKQ6Z0zNX: resolvedLinks[1],
															},
															TDK1WYV5h: {
																KKQ6Z0zNX: resolvedLinks[2],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zdhhX.framer-1danrii, .framer-zdhhX .framer-1danrii { display: block; }",
	".framer-zdhhX.framer-o6v2mw { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-zdhhX .framer-1xxfotg { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-zdhhX .framer-1oqg25v { display: grid; flex: 1 0 0px; gap: 12px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); height: min-content; justify-content: center; padding: 0px; position: relative; width: 1px; }",
	".framer-zdhhX .framer-16zeecp { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; justify-self: start; padding: 0px; position: relative; width: 100%; }",
	".framer-zdhhX .framer-1oiwg61 { aspect-ratio: 1 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 162px); position: relative; width: 1px; }",
	".framer-zdhhX .framer-4ma0pe { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-zdhhX .framer-wjfqrh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-zdhhX .framer-7d874b, .framer-zdhhX .framer-109skd4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-zdhhX .framer-1h7amsi-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-zdhhX.framer-v-13u1434.framer-o6v2mw { padding: 80px 30px 80px 30px; width: 810px; }",
	".framer-zdhhX.framer-v-13u1434 .framer-1xxfotg { gap: 48px; }",
	".framer-zdhhX.framer-v-13u1434 .framer-1oiwg61, .framer-zdhhX.framer-v-1x8wx0r .framer-1oiwg61 { height: var(--framer-aspect-ratio-supported, 200px); }",
	".framer-zdhhX.framer-v-1x8wx0r.framer-o6v2mw { padding: 60px 16px 60px 16px; width: 200px; }",
	".framer-zdhhX.framer-v-1x8wx0r .framer-1xxfotg { flex-direction: column; gap: 48px; }",
	".framer-zdhhX.framer-v-1x8wx0r .framer-1oqg25v, .framer-zdhhX.framer-v-1x8wx0r .framer-4ma0pe { flex: none; width: 100%; }",
	...css2,
	...css,
];
var FramerOxccbqJmn = withCSS(Component, css3, "framer-zdhhX");
var stdin_default3 = FramerOxccbqJmn;
FramerOxccbqJmn.displayName = "SERVICES2";
FramerOxccbqJmn.defaultProps = {
	height: 536,
	width: 1200,
};
addPropertyControls(FramerOxccbqJmn, {
	variant: {
		options: ["YpsE4EfXY", "moNzV090n", "TDK1WYV5h"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerOxccbqJmn,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonPrimaryFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:services2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "TDK1WYV5h",
	md: "moNzV090n",
	xl: "YpsE4EfXY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Services2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var services2_default = ComponentWithRoot;
export { services2_default as default };
