// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c458aa6424685531 "Titen (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-63TWHLYQ.js";
import "./chunks/chunk-RNVUQTXT.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-ILVHS3C2.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-FYMJT4D6.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-4LLJ7Y3K.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-N4SVWGDY.js";
import { stdin_default } from "./chunks/chunk-UNQN4VUP.js";
import "./chunks/chunk-IICRMQVR.js";
import "./chunks/chunk-RZ6XIZ35.js";
import { className, css, fonts } from "./chunks/chunk-MBDBQ6CG.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-2RKPPYFD.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-6TWF3UWX.js";
import { routes } from "./chunks/chunk-B4EDX7DX.js";

// virtual:services
import { Fragment as Fragment6 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/SERVICES-UX9P.js
import { jsx as _jsx6, jsxs as _jsxs6 } from "react/jsx-runtime";
import {
	addFonts as addFonts5,
	addPropertyControls as addPropertyControls6,
	ComponentViewportProvider as ComponentViewportProvider4,
	ControlType as ControlType6,
	cx as cx5,
	getFonts as getFonts4,
	getFontsFromSharedStyle as getFontsFromSharedStyle4,
	getLoadingLazyAtYPosition,
	Image,
	ResolveLinks,
	RichText as RichText4,
	SmartComponentScopedContainer as SmartComponentScopedContainer4,
	useComponentViewport as useComponentViewport5,
	useLocaleInfo as useLocaleInfo5,
	useRouter,
	useVariantState as useVariantState5,
	withCSS as withCSS5,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup5,
	motion as motion6,
	MotionConfigContext as MotionConfigContext5,
} from "unframer";
import * as React5 from "react";
import { useRef as useRef5, useState } from "react";

// /:https://framerusercontent.com/modules/j9PkS7h3icB7llL9isK7/fg4kEOSLiS2UPbjXmL1j/ImYBdMpg2.js
import { jsx as _jsx4, jsxs as _jsxs4 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls4,
	ComponentViewportProvider as ComponentViewportProvider3,
	ControlType as ControlType4,
	cx as cx3,
	getFonts as getFonts3,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getPropertyControls,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer3,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion4,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/kBkaj3LmBqcSU2IkUsBC/kvFSr6fSU7VcYZyNyfaK/Download.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
} from "unframer";
import { motion as motion3 } from "unframer";
var IconType;
(function (IconType2) {
	IconType2["Default"] = "Default";
	IconType2["Custom"] = "Custom";
})(IconType || (IconType = {}));
var SrcType;
(function (SrcType2) {
	SrcType2["Upload"] = "Upload";
	SrcType2["URL"] = "URL";
})(SrcType || (SrcType = {}));
var metaTagSelector = 'meta[name="framer-search-index"]';
function isPublishedSiteOrSSG() {
	if (typeof document === "undefined") return true;
	const metaTag = document.querySelector(metaTagSelector);
	return !!metaTag;
}
function Download(props) {
	const { styleOptions, hoverOptions, iconOptions } = props;
	const {
		backgroundColor,
		color,
		borderRadius,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		gap,
	} = styleOptions;
	const isInPublishedSiteOrSSG = isPublishedSiteOrSSG();
	let downloadURL = void 0;
	if (isInPublishedSiteOrSSG) {
		if (props.srcType === SrcType.URL) downloadURL = props.srcURL;
		if (props.srcType === SrcType.Upload) downloadURL = props.srcFile;
	}
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const getIcon = () => {
		var ref, ref1;
		if (!iconOptions) return;
		const iconStyle = {
			order: iconOptions.alignment === "start" ? 0 : 2,
			flexShrink: 0,
		};
		return iconOptions.type === IconType.Custom &&
			!!((ref = iconOptions.image) === null || ref === void 0
				? void 0
				: ref.src) ? (
			<img
				style={iconStyle}
				alt={
					((ref1 = iconOptions.image) === null || ref1 === void 0
						? void 0
						: ref1.alt) && iconOptions.image.alt.length > 0
						? iconOptions.image.alt
						: "download icon"
				}
				src={iconOptions.image.src}
				width={iconOptions.size}
				height={iconOptions.size}
			/>
		) : (
			<svg
				style={iconStyle}
				xmlns={"http://www.w3.org/2000/svg"}
				width={iconOptions.size}
				height={iconOptions.size}
				fill={iconOptions.color}
				viewBox={"0 0 256 256"}
			>
				<path
					d={
						"M228 152v56a20 20 0 0 1-20 20H48a20 20 0 0 1-20-20v-56a12 12 0 0 1 24 0v52h152v-52a12 12 0 0 1 24 0Zm-108.49 8.49a12 12 0 0 0 17 0l40-40a12 12 0 0 0-17-17L140 123V40a12 12 0 0 0-24 0v83l-19.51-19.49a12 12 0 0 0-17 17Z"
					}
				/>
			</svg>
		);
	};
	const getCursor = () => {
		if (props.srcType === SrcType.URL && props.srcURL) return "pointer";
		if (props.srcType === SrcType.Upload && props.srcFile) return "pointer";
		return "auto";
	};
	const buttonTitle = isInPublishedSiteOrSSG
		? "Download File"
		: "Publish to Download";
	return (
		<motion3.a
			target={"_blank"}
			href={downloadURL}
			download={true}
			title={buttonTitle}
			style={{
				gap,
				fontSize: 16,
				lineHeight: 1,
				fontFamily: "Inter",
				fontWeight: 500,
				width: "max-content",
				...props.style,
				...props.fontControl,
				padding: paddingValue,
				color,
				backgroundColor,
				borderRadius,
				userSelect: "none",
				placeContent: flexAlignSwitch(props.fontControl),
				whiteSpace: "nowrap",
				cursor: getCursor(),
			}}
			whileHover={hoverOptions}
			transition={
				hoverOptions === null || hoverOptions === void 0
					? void 0
					: hoverOptions.transition
			}
		>
			{getIcon()}
			{props.text}
		</motion3.a>
	);
}
Download.displayName = "Download";
addPropertyControls3(Download, {
	text: {
		title: "Text",
		type: ControlType3.String,
		defaultValue: "Download",
	},
	srcType: {
		type: ControlType3.Enum,
		displaySegmentedControl: true,
		title: "Source",
		options: [SrcType.Upload, SrcType.URL],
	},
	srcURL: {
		type: ControlType3.String,
		title: " ",
		placeholder: "../example.pdf",
		hidden: (props) => props.srcType === SrcType.Upload,
	},
	srcFile: {
		type: ControlType3.File,
		title: " ",
		allowedFileTypes: [],
		hidden: (props) => props.srcType === SrcType.URL,
	},
	fontControl: {
		// @ts-ignore - Internal
		type: ControlType3.Font,
		title: "Font",
		controls: "extended",
	},
	iconOptions: {
		type: ControlType3.Object,
		optional: true,
		title: "Icon",
		buttonTitle: "Size, Color",
		controls: {
			type: {
				title: "Type",
				type: ControlType3.Enum,
				options: Object.values(IconType),
				optionTitles: Object.values(IconType),
				displaySegmentedControl: true,
			},
			color: {
				title: "Color",
				type: ControlType3.Color,
				defaultValue: "#FFF",
				hidden: (props) => props.type === IconType.Custom,
			},
			image: {
				title: "File",
				type: ControlType3.ResponsiveImage,
				allowedFileTypes: ["jpg", "png", "svg"],
				hidden: (props) => props.type === IconType.Default,
			},
			size: {
				type: ControlType3.Number,
				displayStepper: true,
				min: 5,
				defaultValue: 16,
				max: 250,
			},
			alignment: {
				title: "Align",
				type: ControlType3.Enum,
				displaySegmentedControl: true,
				options: ["start", "end"],
				optionTitles: ["Start", "End"],
			},
		},
	},
	styleOptions: {
		type: ControlType3.Object,
		title: "Styles",
		buttonTitle: "Button, Font",
		controls: {
			backgroundColor: {
				type: ControlType3.Color,
				title: "Fill",
				defaultValue: "#111",
			},
			color: {
				type: ControlType3.Color,
				defaultValue: "#FFF",
			},
			borderRadius: {
				type: ControlType3.Number,
				title: "Radius",
				displayStepper: true,
				defaultValue: 50,
			},
			padding: {
				title: "Padding",
				type: ControlType3.FusedNumber,
				toggleKey: "paddingPerSide",
				toggleTitles: ["Padding", "Padding per side"],
				defaultValue: 10,
				valueKeys: [
					"paddingTop",
					"paddingRight",
					"paddingBottom",
					"paddingLeft",
				],
				valueLabels: ["T", "R", "B", "L"],
				min: 0,
			},
			gap: {
				title: "Gap",
				type: ControlType3.Number,
				displayStepper: true,
				defaultValue: 5,
			},
		},
	},
	hoverOptions: {
		type: ControlType3.Object,
		title: "Hover",
		buttonTitle: "Effect",
		optional: true,
		controls: {
			scale: {
				type: ControlType3.Number,
				title: "Scale",
				min: 0,
				max: 10,
				displayStepper: true,
				step: 0.01,
				defaultValue: 1.1,
			},
			backgroundColor: {
				type: ControlType3.Color,
				title: "Fill",
				defaultValue: "#333",
				optional: true,
			},
			color: {
				type: ControlType3.Color,
				title: "Color",
				defaultValue: "#FFF",
				optional: true,
			},
			transition: {
				type: ControlType3.Transition,
				title: "Transition",
				defaultValue: {
					type: "spring",
					stiffness: 400,
					damping: 30,
				},
			},
		},
	},
});
var buttonStyles = {
	display: "flex",
	placeItems: "center",
	placeContent: "center",
	textDecoration: "none",
};
var flexAlignSwitch = (fontControlStyles) => {
	if (
		!(fontControlStyles === null || fontControlStyles === void 0
			? void 0
			: fontControlStyles.textAlign)
	) {
		return "left";
	}
	if (fontControlStyles.textAlign === "left") {
		return "flex-start";
	}
	if (fontControlStyles.textAlign === "right") {
		return "flex-end";
	}
	return "center";
};

// /:https://framerusercontent.com/modules/p9F3P8YY9Cj1pfwuFNNy/s2jDJVlAvNrvVUMotWIl/uKqdtKZW0.js
import { jsx as _jsx5, jsxs as _jsxs5 } from "react/jsx-runtime";
import {
	addFonts as addFonts4,
	addPropertyControls as addPropertyControls5,
	ControlType as ControlType5,
	cx as cx4,
	getFontsFromSharedStyle as getFontsFromSharedStyle3,
	Link,
	RichText as RichText3,
	useComponentViewport as useComponentViewport4,
	useLocaleInfo as useLocaleInfo4,
	useVariantState as useVariantState4,
	withCSS as withCSS4,
} from "unframer";
import {
	LayoutGroup as LayoutGroup4,
	motion as motion5,
	MotionConfigContext as MotionConfigContext4,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef4 } from "react";
var enabledGestures2 = {
	WoD2_61FO: {
		hover: true,
	},
};
var serializationHash4 = "framer-k7TMU";
var variantClassNames4 = {
	WoD2_61FO: "framer-v-19r2xxg",
};
function addPropertyOverrides4(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition14 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition4 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext4);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext4.Provider value={contextValue}>
			{children}
		</MotionConfigContext4.Provider>
	);
};
var Variants4 = motion5.create(React4.Fragment);
var getProps4 = ({ buttonText, color, height, id, link, width, ...props }) => {
	return {
		...props,
		AZmVxpo8d:
			color ??
			props.AZmVxpo8d ??
			"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
		bVy6j5ug1: link ?? props.bVy6j5ug1,
		sj9ZoXu_c: buttonText ?? props.sj9ZoXu_c ?? "Button",
	};
};
var createLayoutDependency4 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo4();
	const componentViewport = useComponentViewport4();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		sj9ZoXu_c,
		AZmVxpo8d,
		bVy6j5ug1,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState4({
		defaultVariant: "WoD2_61FO",
		enabledGestures: enabledGestures2,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames4,
	});
	const layoutDependency = createLayoutDependency4(props, variants);
	const sharedStyleClassNames = [className6];
	const scopingClassNames = cx4(serializationHash4, ...sharedStyleClassNames);
	return (
		<LayoutGroup4 id={layoutId ?? defaultLayoutId}>
			<Variants4 animate={variants} initial={false}>
				<Transition4 value={transition14}>
					<Link
						href={bVy6j5ug1}
						motionChild={true}
						nodeId={"WoD2_61FO"}
						scopeId={"uKqdtKZW0"}
					>
						<motion5.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx4(scopingClassNames, "framer-19r2xxg", className8, classNames)} framer-100nitg`}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"WoD2_61FO"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides4(
								{
									"WoD2_61FO-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText3
								__fromCanvasComponent={true}
								className={"framer-15i3jk9"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"XicePqQpX"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-AZmVxpo8d-uKqdtKZW0)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-AZmVxpo8d-uKqdtKZW0": AZmVxpo8d,
								}}
								text={sj9ZoXu_c}
								variants={{
									"WoD2_61FO-hover": {
										"--extracted-r6o4lv":
											"var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides4(
									{
										"WoD2_61FO-hover": {
											children: (
												<React4.Fragment>
													<motion5.p
														className={"framer-styles-preset-11asbfe"}
														data-styles-preset={"NtXagAClV"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54)))",
														}}
													>
														{"Button"}
													</motion5.p>
												</React4.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React4.Fragment>
									<motion5.p
										className={"framer-styles-preset-11asbfe"}
										data-styles-preset={"NtXagAClV"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-AZmVxpo8d-uKqdtKZW0))",
										}}
									>
										{"Button"}
									</motion5.p>
								</React4.Fragment>
							</RichText3>
							<motion5.div
								className={"framer-1cldinx"}
								data-framer-name={"Line 1"}
								layoutDependency={layoutDependency}
								layoutId={"SANwfvGX1"}
								style={{
									backgroundColor: AZmVxpo8d,
									opacity: 0.3,
								}}
							/>
							<motion5.div
								className={"framer-dqjciv"}
								data-framer-name={"Line 2"}
								layoutDependency={layoutDependency}
								layoutId={"bJWWPs1Mf"}
								style={{
									backgroundColor:
										"var(--token-8d460569-8739-491b-a250-77004a818d0e, rgb(195, 96, 54))",
								}}
							/>
						</motion5.a>
					</Link>
				</Transition4>
			</Variants4>
		</LayoutGroup4>
	);
});
var css11 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-k7TMU.framer-100nitg, .framer-k7TMU .framer-100nitg { display: block; }",
	".framer-k7TMU.framer-19r2xxg { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 4px 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-k7TMU .framer-15i3jk9 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-k7TMU .framer-1cldinx { bottom: 0px; flex: none; height: 1px; left: 0px; overflow: hidden; position: absolute; width: 100%; z-index: 1; }",
	".framer-k7TMU .framer-dqjciv { bottom: 0px; flex: none; height: 1px; left: 0px; overflow: hidden; position: absolute; width: 0%; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-k7TMU.framer-19r2xxg { gap: 0px; } .framer-k7TMU.framer-19r2xxg > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-k7TMU.framer-19r2xxg > :first-child { margin-top: 0px; } .framer-k7TMU.framer-19r2xxg > :last-child { margin-bottom: 0px; } }",
	".framer-k7TMU.framer-v-19r2xxg.hover .framer-dqjciv { width: 100%; }",
	...css6,
];
var FrameruKqdtKZW0 = withCSS4(Component4, css11, "framer-k7TMU");
var stdin_default6 = FrameruKqdtKZW0;
FrameruKqdtKZW0.displayName = "Button/Text Line";
FrameruKqdtKZW0.defaultProps = {
	height: 18,
	width: 50,
};
addPropertyControls5(FrameruKqdtKZW0, {
	sj9ZoXu_c: {
		defaultValue: "Button",
		displayTextArea: false,
		title: "Button Text",
		type: ControlType5.String,
	},
	AZmVxpo8d: {
		defaultValue:
			"var(--token-9fe7799f-86f2-493e-bc6f-9f47ef410593, rgb(18, 18, 18))",
		title: "Color",
		type: ControlType5.Color,
	},
	bVy6j5ug1: {
		title: "Link",
		type: ControlType5.Link,
	},
});
addFonts4(
	FrameruKqdtKZW0,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle3(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/SERVICES-UX9P.js
var ButtonPrimaryFonts = getFonts4(stdin_default);
var MotionDivWithFX = withFX(motion6.div);
var DownloadFonts2 = getFonts4(stdin_default5);
var ButtonTextLineFonts = getFonts4(stdin_default6);
var cycleOrder3 = ["l8whQih9a", "wdQbvkrFx", "JU_XBdbLf"];
var serializationHash5 = "framer-xbdWH";
var variantClassNames5 = {
	JU_XBdbLf: "framer-v-u0qv0y",
	l8whQih9a: "framer-v-1nio7rc",
	wdQbvkrFx: "framer-v-197vd4y",
};
function addPropertyOverrides5(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition15 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 18,
};
var transition2 = {
	damping: 55,
	delay: 0.05,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var Transition5 = ({ value, children }) => {
	const config = React5.useContext(MotionConfigContext5);
	const transition = value ?? config.transition;
	const contextValue = React5.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext5.Provider value={contextValue}>
			{children}
		</MotionConfigContext5.Provider>
	);
};
var Variants5 = motion6.create(React5.Fragment);
var humanReadableVariantMap3 = {
	Desktop: "l8whQih9a",
	Phone: "JU_XBdbLf",
	Tablet: "wdQbvkrFx",
};
var getProps5 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "l8whQih9a",
	};
};
var createLayoutDependency5 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component5 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const fallbackRef = useRef5(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React5.useId();
	const { activeLocale, setLocale } = useLocaleInfo5();
	const componentViewport = useComponentViewport5();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		...restProps
	} = getProps5(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState5({
		cycleOrder: cycleOrder3,
		defaultVariant: "l8whQih9a",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames5,
	});
	const layoutDependency = createLayoutDependency5(props, variants);
	const sharedStyleClassNames = [className, className4, className2, className3];
	const scopingClassNames = cx5(serializationHash5, ...sharedStyleClassNames);
	const router = useRouter();

    const [price, setPrice] = useState('500000');
    const [afa, setAfa] = useState('5');
    const [taxRate, setTaxRate] = useState('42');
    const [years, setYears] = useState('12');

    const priceNum = parseFloat(price) || 0;
    const afaRate = parseFloat(afa) || 0;
    const taxRateNum = parseFloat(taxRate) || 0;
    const yearsNum = parseInt(years) || 0;

    const yearlyAfa = priceNum * afaRate / 100;
    const yearlySavings = yearlyAfa * taxRateNum / 100;
    const totalSavings = yearlySavings * yearsNum;

    const format = (n) => n.toLocaleString('de-DE', { style: 'currency', currency: 'EUR' });

	return (
		<LayoutGroup5 id={layoutId ?? defaultLayoutId}>
			<Variants5 animate={variants} initial={false}>
				<Transition5 value={transition15}>
					<motion6.section
						{...restProps}
						{...gestureHandlers}
						className={cx5(
							scopingClassNames,
							"framer-1nio7rc",
							className8,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"l8whQih9a"}
						ref={refBinding}
						id="tax-calculator"
						style={{
							...style,
						}}
						{...addPropertyOverrides5(
							{
								JU_XBdbLf: {
									"data-framer-name": "Phone",
								},
								wdQbvkrFx: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion6.div
							className={"framer-1wkkhf8"}
							data-framer-name={"Inner"}
							layoutDependency={layoutDependency}
							layoutId={"l_yqZ91Ia"}
						>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-nra19a"}
								data-framer-name={"Title Section"}
								layoutDependency={layoutDependency}
								layoutId={"ntcCIc6Bx"}
							>
								<motion6.div
									className={"framer-1bve2ih"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"i4BiJc_gf"}
								>
									<RichText4
										__fromCanvasComponent={true}
										className={"framer-1jn2rpc"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"VmSY0ZMV3"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion6.p
												className={"framer-styles-preset-11asbfe"}
												data-styles-preset={"NtXagAClV"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-7f5b7011-acac-4051-97f5-7a6faa0b26dc, rgba(18, 18, 18, 0.8)))",
												}}
											>
												{"Steuer-Vorteil"}
											</motion6.p>
										</React5.Fragment>
									</RichText4>
									<RichText4
										__fromCanvasComponent={true}
										className={"framer-1sxujqk"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"FX6bvlUXG"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion6.h2
												className={"framer-styles-preset-rdnt0j"}
												data-styles-preset={"wIgsXR7Fc"}
											>
												{"Ihr persönlicher AfA-Rechner"}
											</motion6.h2>
										</React5.Fragment>
									</RichText4>
								</motion6.div>
								<motion6.div
									className={"framer-1mvaxxd"}
									data-framer-name={"Details"}
									layoutDependency={layoutDependency}
									layoutId={"L30c4tZI1"}
								>
									<RichText4
										__fromCanvasComponent={true}
										className={"framer-117oirn"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"s6XnuWexN"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion6.p
												className={"framer-styles-preset-144gy8o"}
												data-styles-preset={"qA7GDH1GX"}
											>
												{
													"Berechnen Sie hier Ihren individuellen Steuervorteil durch die Abschreibung für Abnutzung (AfA) bei einer Investition in eine Denkmalimmobilie."
												}
											</motion6.p>
										</React5.Fragment>
									</RichText4>
								</motion6.div>
							</MotionDivWithFX>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-m75gpm"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"BabrnzTc6"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(100 +
													((componentViewport?.height || 200) - 200 - 2544.4) /
														2) +
												0 +
												330.4 +
												63,
										),
										pixelHeight: 1600,
										pixelWidth: 2400,
										sizes: `calc(min(max(${componentViewport?.width || "100vw"} - 100px, 1px), 1440px) * 0.5909)`,
										src: "https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg",
										srcSet:
											"https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg 2400w",
									}}
									className={"framer-1avd0nm"}
									layoutDependency={layoutDependency}
									layoutId={"E0VNppowi"}
									{...addPropertyOverrides5(
										{
											JU_XBdbLf: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	120 -
																	3359.4) /
																	2) +
															0 +
															395.4 +
															0 +
															608,
													),
													pixelHeight: 1600,
													pixelWidth: 2400,
													sizes: `min(max(${componentViewport?.width || "100vw"} - 32px, 1px), 1440px)`,
													src: "https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg",
													srcSet:
														"https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg 2400w",
												},
											},
											wdQbvkrFx: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	160 -
																	2698.4) /
																	2) +
															0 +
															322.4 +
															63,
													),
													pixelHeight: 1600,
													pixelWidth: 2400,
													sizes: `calc(min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1440px) * 0.5909)`,
													src: "https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg",
													srcSet:
														"https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/WFgDM3tgvDIdwpIYFIwEKYBTlI.jpg 2400w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
                                <div className="calculator-container">
                                    <div className="input-grid">
                                        <div className="input-group">
                                            <label>Kaufpreis (€)</label>
                                            <input type="number" value={price} onChange={e => setPrice(e.target.value)} placeholder="Kaufpreis (€)" />
                                        </div>
                                        <div className="input-group">
                                            <label>AfA-Satz (%)</label>
                                            <input type="number" value={afa} onChange={e => setAfa(e.target.value)} placeholder="AfA-Satz (%)" />
                                        </div>
                                        <div className="input-group">
                                            <label>Einkommensteuersatz (%)</label>
                                            <input type="number" value={taxRate} onChange={e => setTaxRate(e.target.value)} placeholder="Einkommensteuersatz (%)" />
                                        </div>
                                        <div className="input-group">
                                            <label>Laufzeit (Jahre)</label>
                                            <input type="number" value={years} onChange={e => setYears(e.target.value)} placeholder="Laufzeit (Jahre)" />
                                        </div>
                                    </div>
                                    <div className="results">
                                        <p>Jährliche AfA: <strong>{format(yearlyAfa)}</strong></p>
                                        <p>Steuerersparnis pro Jahr: <strong>{format(yearlySavings)}</strong></p>
                                        <p>Steuerersparnis gesamt: <strong>{format(totalSavings)}</strong></p>
                                    </div>
                                </div>
							</MotionDivWithFX>
						</motion6.div>
					</motion6.section>
				</Transition5>
			</Variants5>
		</LayoutGroup5>
	);
});
var css12 = [
    ".framer-xbdWH .calculator-container { display: flex; flex-direction: column; gap: 24px; width: 100%; color: #121212; padding: 24px; background-color: rgba(255,255,255,0.8); border-radius: 10px; }",
    ".framer-xbdWH .input-grid { display: grid; grid-template-columns: 1fr; gap: 16px; }",
    "@media (min-width: 600px) { .framer-xbdWH .input-grid { grid-template-columns: repeat(2, 1fr); } }",
    ".framer-xbdWH .input-group { display: flex; flex-direction: column; gap: 4px; }",
    ".framer-xbdWH .input-group label { font-size: 14px; color: rgba(18, 18, 18, 0.8); }",
    ".framer-xbdWH .input-group input { border: 1px solid rgba(18, 18, 18, 0.3); padding: 8px 12px; border-radius: 5px; font-size: 16px; width: 100%; background-color: white; }",
    ".framer-xbdWH .results { display: flex; flex-direction: column; gap: 8px; text-align: left; padding: 16px; border-top: 1px solid rgba(18, 18, 18, 0.1); }",
    ".framer-xbdWH .results p { font-size: 16px; }",
    ".framer-xbdWH .results strong { font-weight: bold; }",
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xbdWH.framer-1iu19uz, .framer-xbdWH .framer-1iu19uz { display: block; }",
	".framer-xbdWH.framer-1nio7rc { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 50px 100px 50px; position: relative; width: 1200px; }",
	".framer-xbdWH .framer-1wkkhf8 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-xbdWH .framer-nra19a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-1bve2ih { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 750px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-1jn2rpc, .framer-xbdWH .framer-1sxujqk, .framer-xbdWH .framer-1fi8lcm, .framer-xbdWH .framer-dhoq9h, .framer-xbdWH .framer-lpi4wl, .framer-xbdWH .framer-1yxkrdy { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-xbdWH .framer-1mvaxxd { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-117oirn { flex: 1 0 0px; height: auto; max-width: 550px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-xbdWH .framer-o4d3ha-container, .framer-xbdWH .framer-ir5gz1-container, .framer-xbdWH .framer-3j4yel-container, .framer-xbdWH .framer-ezpsqs-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-xbdWH .framer-m75gpm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-xbdWH .framer-1avd0nm { aspect-ratio: 1.4444444444444444 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 450px); overflow: hidden; position: relative; width: 59%; }",
	".framer-xbdWH .calculator-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-xbdWH.framer-v-197vd4y.framer-1nio7rc { padding: 80px 30px 80px 30px; width: 810px; }",
	".framer-xbdWH.framer-v-197vd4y .framer-1wkkhf8 { gap: 56px; }",
	".framer-xbdWH.framer-v-197vd4y .framer-1mvaxxd { gap: 100px; justify-content: center; }",
	".framer-xbdWH.framer-v-197vd4y .framer-117oirn { max-width: unset; }",
	".framer-xbdWH.framer-v-197vd4y .framer-1avd0nm { height: var(--framer-aspect-ratio-supported, 138px); }",
	".framer-xbdWH.framer-v-u0qv0y.framer-1nio7rc { padding: 60px 16px 60px 16px; width: 390px; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-1wkkhf8 { gap: 48px; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-1mvaxxd { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 48px; justify-content: center; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-m75gpm { flex-direction: column; gap: 32px; }",
	".framer-xbdWH.framer-v-u0qv0y .framer-1avd0nm { height: var(--framer-aspect-ratio-supported, 138px); order: 1; width: 100%; }",
	".framer-xbdWH.framer-v-u0qv0y .calculator-container { flex: none; order: 0; width: 100%; }",
	...css,
	...css4,
	...css2,
	...css3,
];
var FramerdKghMdWSg = withCSS5(Component5, css12, "framer-xbdWH");
var TaxCalculator = FramerdKghMdWSg;
TaxCalculator.displayName = "TaxCalculator";
TaxCalculator.defaultProps = {
	height: 2583,
	width: 1200,
};
addPropertyControls6(TaxCalculator, {
	variant: {
		options: ["l8whQih9a", "wdQbvkrFx", "JU_XBdbLf"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType6.Enum,
	},
});
addFonts5(
	TaxCalculator,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonPrimaryFonts,
		...DownloadFonts2,
		...ButtonTextLineFonts,
		...getFontsFromSharedStyle4(fonts),
		...getFontsFromSharedStyle4(fonts4),
		...getFontsFromSharedStyle4(fonts2),
		...getFontsFromSharedStyle4(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:services
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JU_XBdbLf",
	md: "wdQbvkrFx",
	xl: "l8whQih9a",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(TaxCalculator, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c458aa64246855310a081e407e3bb5c28a3ebfd49fe6ff2ee0892f22890665f4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={TaxCalculator}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, TaxCalculator);
var tax_calculator_default = ComponentWithRoot;
export { tax_calculator_default as default };
